### ISSUE TITLE
Examples - error loading pages 0 to 0

### ISSUE THREAD

**Issue by yslee-ag** [6pac/SlickGrid#1000]
### Describe the bug

error loading pages 0 to 0

- AJAX-loading data with search
http://6pac.github.io/SlickGrid/examples/example6-ajax-loading.html

- AJAX-loading data, second example
http://6pac.github.io/SlickGrid/examples/example6-ajax-loading-yahoo.html

### Reproduction

- AJAX-loading data with search
http://6pac.github.io/SlickGrid/examples/example6-ajax-loading.html

- AJAX-loading data, second example
http://6pac.github.io/SlickGrid/examples/example6-ajax-loading-yahoo.html

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| SlickGrid | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Not really supported anymore since we have nothing to test against. All these APIs are now requiring API Keys and no longer work anonymously (which is understandable nowadays with all the security issues popping up every week). The error thrown is entirely normal because the API no longer work without a key, so... the best suggestion would be to try them out with your own APIs since we will no longer work on these 2 plugins neither the demos. Lastly, if you have any problems with the plugins then contribute a fix, otherwise nothing will happen from our side.
