### ISSUE TITLE
Can example have select/dropdown sample

### ISSUE THREAD

**Issue by ericxin1982** [6pac/SlickGrid#1062]
### Clear and concise description of the problem

I am very new to SlickGrid, and I see all examples, that is awesome. I am curious how it looks like select/dropdown feature for grid active inline edit but is not there. Would you please add that specific example there, so I can learn.

### Suggested solution

It is not a feature request, it is example request, sorry to confuse you guys.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by 6pac** [comment]
Have a look under ```Bootstrap, Dynamic Grids and Third Party component editors``` -> ```[Select2 javascript drop-down editor](http://6pac.github.io/SlickGrid/examples/example-select2-editor.html)

**Comment by ericxin1982** [comment]
Excellent, Thanks for your help.

**Comment by ericxin1982** [comment]
@6pac 

Can you give me an example with simple select, select2 use jquery, for less library consideration, I look for independent library better.

**Comment by 6pac** [comment]
There is no example for that, but Select2 uses a regular HTML select as a base. It should be easy to remove jQuery and the Select2 parts.

**Comment by ericxin1982** [comment]
OK, I see. I would try a bit.

**Comment by ghiscoding** [comment]
It would be better to ask these kind of questions on Stack Overflow and if you search on the website, you'll find this SO that might be what you need to get started. You can also read the [Writing-custom-cell-editors](https://github.com/6pac/SlickGrid/wiki/Writing-custom-cell-editors) Wiki

[SlickGrid select editor](https://stackoverflow.com/questions/3211956/slickgrid-select-editor)

If you want an all-assembled project, you can take a look at [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which has built-in single/multiple select.

**Comment by ericxin1982** [comment]
Sure, thanks.
