### ISSUE TITLE
DataView getFilteredItems seems to be not respecting sorting

### ISSUE THREAD

**Issue by legezam** [6pac/SlickGrid#1065]
### Describe the bug

After calling `sort` and `setFilter` on `DataView`, calling `getFilteredItems` returns the items not reflecting the sort order.

### Reproduction

I can create a simple one if necessary but this is somewhat apparent even in the codebase of SlickGrid: the method `sort` in `DataView` doesn't update the `filteredItems` collection, only the `items` collection.

### Which Framework are you using?

Other

### Environment Info

```shell
System:
    OS: Linux 6.10 Fedora Linux 40 (Workstation Edition)
    CPU: (22) x64 Intel(R) Core(TM) Ultra 9 185H
    Memory: 43.73 GB / 62.23 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/bin/node
    npm: 10.5.0 - /usr/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I think that is normal behavior and should be handled on userland because the filtered data is a separate array and sorting both arrays would slow down the process which is why it's better handled on userland. Or maybe the only acceptable solution would be to add an extra argument that would be optional to also sort the `filteredItems` array as well (would default to false because of perf consideration that I mentioned above).

https://github.com/6pac/SlickGrid/blob/54bb8d5d9a18689d671e5b43b454ae49f3c2d972/src/slick.dataview.ts#L335-L349

However I took a quick look at the code and I thought that calling `dv.refresh()` since might help because it's calling the internal `.recalc()` which is then calling

https://github.com/6pac/SlickGrid/blob/54bb8d5d9a18689d671e5b43b454ae49f3c2d972/src/slick.dataview.ts#L1335-L1345

which is then calling `.getFilteredAndPagedItems()`

https://github.com/6pac/SlickGrid/blob/54bb8d5d9a18689d671e5b43b454ae49f3c2d972/src/slick.dataview.ts#L1308-L1316

and finally inside that protected method, it seems to be where the `filteredItems` array is being assigned, which is why I'm saying that calling `dv.refresh()` might work but I haven't tested it.

https://github.com/6pac/SlickGrid/blob/54bb8d5d9a18689d671e5b43b454ae49f3c2d972/src/slick.dataview.ts#L1223-L1240

..but then I realized that `.refresh()` is actually called directly by the `.sort()`, so it's a bit surprising that it's not sorted, perhaps it only reassigns when any of the "hints" are enabled (it might be since that seems to be only for filtering)?

**Comment by legezam** [comment]
@ghiscoding , thanks for the detailed analysis, could you give me directions to setting those hints you mentioned here, please:

>when any of the "hints" are enabled (it might be since that seems to be only for filtering)?

**Comment by ghiscoding** [comment]
I've never used them myself because I think it requires `inlineFilter` to be enabled but I guess it's mostly meant for filtering like I said earlier

Example https://6pac.github.io/SlickGrid/examples/example-optimizing-dataview.html

https://github.com/6pac/SlickGrid/blob/54bb8d5d9a18689d671e5b43b454ae49f3c2d972/examples/example-optimizing-dataview.html#L156-L171

and from my previous post, you can see them being used as a condition in the SlickDataView starting on line 1234

**Comment by ghiscoding** [comment]
Just adding console log of `dataView.getFilteredItems()` into the [Example 4 - ESM](https://6pac.github.io/SlickGrid/examples/example4-model-esm.html), I just can't replicate your issue since I the same order as in the UI as shown in the animated gif below. The console logs that I added where in the `onSort` and `onPagingInfoChanged` events

![EfaO9iWIcq](https://github.com/user-attachments/assets/9b1aa6b3-5eb7-43fd-8bf0-82d2a985779a)

**Comment by ghiscoding** [comment]
in that case you could also take a look at my other repo [Slickgrid-React](https://github.com/ghiscoding/slickgrid-react)
