### ISSUE TITLE
Undocumented breaking change: showCellSelection option - why is it needed?

### ISSUE THREAD

**Issue by evil-shrike** [6pac/SlickGrid#122]
In `setActiveCellInternal` method there was a breaking change introduced - added `showCellSelection` check for setting a row a active. After I updated from 2.1 selecting rows breaks.
Before:
```
        $(activeCellNode).addClass("active");
        $(rowsCache[activeRow].rowNode).addClass("active");
```
After:
```
        if (options.showCellSelection) {
        $(activeCellNode).addClass("active");
        $(rowsCache[activeRow].rowNode).addClass("active");
        }
```
It's the only place where `showCellSelection` is used. No any mention in wiki/issues.
Could you tell why did you introduce this change?
Also it's very pity that there was no any note/issue/warning/comment/anything. It makes look this repo as very unstable.
How many did you do such changes?

**Comment by 6pac** [comment]
Apologies about that. That change was clearly intended to have a default option value set to true so that it was not breaking. I have just added a commit to add that option default.

I have my own private branch which proceeds in parallel with the public one. Every so often I sync the changes between the two. The option value must have gotten overlooked.
I try to keep things pretty tight, but it's great to have people testing the public version. I'm not perfect, and your feedback has saved someone else the same headache. The best I can do is react promptly to issue reports.
