### ISSUE TITLE
[Question] to VueJS

### ISSUE THREAD

**Issue by fvelcker** [6pac/SlickGrid#129]
Hello,

It is just a simple question and sorry if it is not the right place to ask. But as this Slickgrid fork and community seems to be the largest, I try my chance.

As some of you know well the source code of Slickgrid, I was wondering if you have any idea how complicated will be to build a Slickgrid VueJS component, so without jQuery at all, and if you think it is worth it.
Because let's face it, Slickgrid is really the fastest and the best written grid (and I am still using the original!). I tried some others and I always wonder why I am using another one...

Well, that's it,
Thanks all
PS: I am also wondering the same but without any dependencies at all, just plain JS. So if you have any inputs or comments as well on that...

**Comment by 6pac** [comment]
Hi Florian,

I'm not familiar with VueJS. But several people have mentioned trying to rewrite Slickgrid to remove various dependencies.
The first one is the dependency on the custom event.drag and event.drop libraries.
Then the dependency on jQueryUI for sortables (jQueryUI in particular has some conflicts with Bootstrap, which is another challenge, which is why there is an example page for that ...)
Finally the dependency on jQuery itself.

@DimitarChristoff has removed the first two, I understand. I haven't had time to follow this up, but I really should. I believe he has shifted to a smaller interaction library though, so this is a new dependency.
https://github.com/6pac/SlickGrid/issues/41

The jQuery dependency would be quite a bit more involved to remove (this would be the plain JS version). This is as far as I got:
https://github.com/6pac/SlickGrid/issues/65
It would be great to do, but a long and painful process to go through. There is no way I have time. But if someone else is keen enough to do it, I'm happy to adopt it once it's reliable.

You're probably aware of the history, but the great strength of jQuery is its cross browser support. It takes all the crazy differences between browsers and unifies them into a single simple method. As browsers slowly become more standards based (this has only happened in the last few years), and javascript becomes more powerful, we may be able to move away from jQuery to pure JS solutions, but due to legacy support, it will be around for a while yet.

**Comment by fvelcker** [comment]
Hello,

Thanks for taking the time to reply. 
I can imagine it will a long process to rewrite. I am not really familiar with vueJS neither, we are going use it at work... I have to motivate myself to start the adventure !

(And, by the way, thanks for maintaining Slickgrid and its community !)

**Comment by taavi-halkola** [comment]
@fvelcker If its completely out of the table for you to use jQuery with VueJs then you might be out of luck. From personal experience, you can get SlickGrid(with jQuery i'm afraid) to work with VueJs. Sorry to bring up an old issue, just letting VueJs people know it is possible.
