### ISSUE TITLE
CellExternalCopyManager don't seem to work with SlickGrid's DataView

### ISSUE THREAD

**Issue by tesdevuk** [6pac/SlickGrid#131]
I've hit the same snag as mentioned on a SlickGrid Google group.

https://groups.google.com/forum/#!topic/slickgrid/eN68pH_DSlw

Rick Jones claims to have reworked CellExternalCopyManager but no details or code provided.

Has this already been addressed?

Any examples?

**Comment by 6pac** [comment]
I've been able to tweak the CellExternalCopyManager to write to the dataview (it's a one liner), but that brings up the question of whether doing that is a good idea.
At the moment, each column either has an editor, or there is an overall getter/setter for the whole grid. The issue is that to copy and paste a block from anywhere to anywhere, the data copied/pasted must be in text format. If data is copied direct, then if the columns of the copy/paste area are not aligned, we might end up copying say a date value into a column that has text data.
So enforcing the requirement for the editor is the way CellExternalCopyManager uses to make sure that text data can be converter to and from the native data type of the column.

I think on balance, rather than changing this, it would be better just to make sure all columns have a text editor. Or, if all columns are text, then use the getter/setter.

Opinions?

**Comment by taavi-halkola** [comment]
@6pac Got the CellExternalCopyManager to work decently with dataview as is. There were some float editors as well which did bring up some problems with cell validation and value formats. I wouldn't change the current functionality. Leave the data value validation/handling to the user. Ended up using the `CellExternalCopyManager.clipboardCommandHandler` to take care of any incorrect data type before the `editcommand.execute()`.
