### ISSUE TITLE
Horizonal scroll appears too easily

### ISSUE THREAD

**Issue by simon1tan** [6pac/SlickGrid#162]
I duplicated SLickGrid example 2 on my page and am finding that the horizontal scroll is appearing rather quickly even though I have plenty of width in my container. It looks like an extra column exists as the last column. Is there an option to remove that or autowidth? You can see an example of this issue on Example11(http://6pac.github.io/SlickGrid/examples/example11-autoheight.html). Example11 should be loaded without a horizontal scrollbar since everything already fits. I can understand if the container width was specified and was too small, the horizontal scrollbar would be 
Note: just tried this in Chrome, the horizontal scroll bar does not appear in Example11 so may be a Firefox (55) related issue. I told myself not to use FIrefox anymore but bad habits.

**Comment by ghiscoding** [comment]
I tried and do see that behavior in almost all browsers (Firefox, IE & even Edge), only Chrome doesn't have the issue, which is awkward. It seems to be a problem with the `autoHeight` implementation since it goes away after fixing the height in CSS and disabling the `autoHeight`. 

Side note, I never personally used the `autoHeight` as I prefer to have a scrolling in the grid itself rather than the browser scrolling which could be huge with thousand of lines. 
You might want to take a look at a new example that I recently added for [Grid auto-resize on browser resize](http://6pac.github.io/SlickGrid/examples/example15-auto-resize.html), I have been using that for a while and the end users mostly like that better.

**Comment by simon1tan** [comment]
Thanks @ghiscoding. I did stumble across the auto-resize example but felt awkward adding custom code. I was thinking there would be an option but I will use this. Perhaps this can be implement as an option in the future.

**Comment by ghiscoding** [comment]
You mean a separate Slick Plugin? That could be an idea, though I already have 2 other PR waiting in the queue (Grid Menu is my biggest one), I will wait until those are merged before working on something else. Thanks for the suggestion

BTW, I'm working on an Angular library and the auto-resize is different than the actual code that I posted in the example just because we don't use jquery directly in Angular but I still wanted to share the resizer with everyone to show that it's doable. Also I prefer to not touch the SlickGrid core as much as possible, doing it inside an example was easier to get it approved and merged :)

**Comment by 6pac** [comment]
Apologies for this @ghiscoding, I'm the bottleneck. Just need to do routine checking, I'm just really busy at the moment. May have time next weekend.

**Comment by ghiscoding** [comment]
@6pac no worries, it gave me time to refine the Plugin and fixed couple of minor issues that I found while having it in production. It's now stable and you can merge whenever you want, there's no rush as I'm using the new Plugin files I created in the PR, I'll just change my source when you will have them merged. Thanks

**Comment by fournm** [comment]
I've got a fix for this issue--I'll open a PR, but in short, getColumnHeaderWidths always assumes scrollbar instead of taking into account options.autoHeight

**Comment by 6pac** [comment]
merged. thanks @fournm. I think this issue is properly closed now,
