### ISSUE TITLE
Show header row, dont display filters

### ISSUE THREAD

**Issue by Tpona** [6pac/SlickGrid#164]
If SlickGrid component was created with flag showHeaderRow:false and then you set it visible using method grid.setHeaderRowVisibility(true), filters will not be shown.

Without changing core code problem can be solved so:
```
grid.setHeaderRowVisibility(true);
grid.setColumns(grid.getColumns()); // now filters exists
```

**Comment by ghiscoding** [comment]
The Header Row can be used for something else than just filters, even though most people use it for the filters. Also filters are custom and are not at all part of the core, you have to program them as you see fit, most of the time it's an input filter but in some cases a select dropdown is better which is why it's not part of the core grid. If you look at the [example - header row](http://6pac.github.io/SlickGrid/examples/example-header-row.html), you will see that the code as a for loop to build the filters, again that is not part of the core and should not be.

I don't see the point in changing anything there.

**Comment by Tpona** [comment]
Ok, but my post not about it. 
Why if in this example i set showHeaderRow to false, then if i call `grid.setHeaderRowVisibility(true);`
header inputs not displayed?

**Comment by 6pac** [comment]
Hi @Tpona, it's a bit tricky. If you start with ```showHeaderRow:false```, the HTML elements of the row won't even be *rendered*. You need to set it to ```true```, then hide it in a manual init. After that, the filter can show or hide it.
This is a bit awkward and I've been thinking of changing the trigger mechanism so it's easier to do what you want. Will get around to it sometime soon.
Ben Mc (@6pac)
