### ISSUE TITLE
Grouping formatter doesnt use formatted value

### ISSUE THREAD

**Issue by javastud** [6pac/SlickGrid#18]
When i use a Key-Value Map formatter in column definition and after grouping by this column the value is not formatted. And also no other way to invoke it manually since group formatter doesnt have a reference to the column definition.

**Comment by 6pac** [comment]
Hi javexpress, 
I don't have a lot of time right now. It might take me a week or so to answer this. 
If you could make up a working sample in your forked repo or in jsFiddle, that would save me time. A pull request with suggested changes would save even more.

In some ways SlickGrid is a toolkit, and customisation is expected because all the different use cases vary to widely. Don't be afraid to get in there and change stuff.
