### ISSUE TITLE
There is no way to determine the grouping rows in double click

### ISSUE THREAD

**Issue by javastud** [6pac/SlickGrid#19]
I use grid.onDblClick.subscribe(function(e, args) .....
When i click the grouping header, the args doesnt have a flag for this.
When i click the total row, the args also doesnt have a flag for this.

Thank you in advance.

**Comment by ghiscoding** [comment]
I know it's old but I looked a little and I think you do have access to that but you're not looking at the right place. 

First of all, there's no grouping at all in the `grid.js` and so you will never ever have that flag in there since all you have is the `grid` object. However your grouping is most probably done via the the `DataView` and you should have a reference to that object, with that reference, you can just call the `dataView.getGrouping()` and you should be good to go.

Remember that the `DataView` is totally independent from the `Grid` and the `Grid` has no reference whatsoever to the `DataView`

I think this issue can be closed
