### ISSUE TITLE
bitwise OR typo

### ISSUE THREAD

**Issue by mblaney** [6pac/SlickGrid#196]
hey, I'm pretty sure this is a typo at: https://github.com/6pac/SlickGrid/blob/master/slick.editors.js#L216-L217

I've changed it to:
 ` } else if (!rtn) {`
`rtn = 0;`

as it was OR'ing away my decimal places :-)

**Comment by 6pac** [comment]
Good catch! In the end, changed it to ```rtn = rtn || 0;``` since there's no javascript operator like ```rtn ||= 0;``` which is what was intended.

**Comment by ghiscoding** [comment]
I was looking to see why bitwise `i | 0` is used in SlickGrid code and came across this issue and comment

> there's no javascript operator like `rtn ||= 0;` which is what was intended.

so that comment isn't true anymore, ES2021 now has `||=` local assignment operator, see this article
https://www.howtogeek.com/devops/whats-new-in-the-es2021-standard-for-javascript/

we will be able to use this operator if we wanted to in our upcoming v5 with TypeScript support :)
---

On a side note, I still wonder why the original author used `i | 0` to parse integer, I wonder if that is better perf than just doing `+i` which I opted to switch to since bitwise are discouraged by eslint

**Comment by 6pac** [comment]
No worries, I support moving forwards as long as we support the oldest version that's still active (ie. I've really only just moved on to ES6). This is not because I'm against it in any way, but us old salt programmers have to support our clients needs, and when that is government or corporations, they call the shots.

I've aware that TS can be transpiled to any version of ES, and I think that's the ultimate answer. TS conversion is on my list and I don't even think it would take that long, but my list is pretty long!!!

Re parsing, yeah bitwise is no longer really acceptable IMO.
