### ISSUE TITLE
Filter doesn't redraw the grid

### ISSUE THREAD

**Issue by RealRegatta** [6pac/SlickGrid#2]
When filtering on the data, if the n new rows are identicals to the n first current rows then no diff is detected and the grid is not refreshed
Try with the [fiddle] (http://jsfiddle.net/hLf0d5mL/3/) : 
    * Filter with 'abcd'
    * The first row is not filtered
    * Filter with 'zzzz'
    * The last row is filtered

The issue is in the slick.dataview.js script in the method getRowDiffs which don't return diff if the n new rows are identical to the n first current rows

**Comment by 6pac** [comment]
Your event assignments need to look like: 

    dataView = new Slick.Data.DataView();
    dataView.setFilter(filter);
    dataView.onRowsChanged.subscribe(function (e, args) {
        grid.invalidateRows(args.rows);
        grid.render();
    });
	dataView.onRowCountChanged.subscribe(function (e, args) {
		grid.invalidateRows(args.rows);
        grid.render();
	});

It doesn't work properly without the onRowCountChanged. Check out the model example.
There has been some discussion about creating a single event that handles both, but no action has been taken yet.

**Comment by RealRegatta** [comment]
> It doesn't work properly without the onRowCountChanged
Yes because the getRowDiffs don't return diff if the n new rows are identical to the n first current rows.
The solution is not to circumvent the bug but fix the bug!

**Comment by 6pac** [comment]
This is how you need to interpret it:
(a) the row count has changed - call event
(b) the rows have not changed because the one row that is now in the set is the same as the row that was there before - don't call event

It's a matter of interpretation, and the rest of the render code is set to interpret it this way. Changing it would be certain to require far reaching changes.
