### ISSUE TITLE
Rowdetails Scrolling item off screen looses current state

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#201]
@ghiscoding 

New issue regarding Rowdetails view.

Assuming I have a label in the view "Label X"
Then assuming I change it to "Label Y"

If I then scroll it off the top of the screen and scroll it back on it returns to "Label X".

Need some way to tell when the view is about to be removed from view so that I can save it's state

**EDIT**
Static content is fine

**Comment by ghiscoding** [comment]
@SatanEnglish 
I merged the PR already, subsequent fixes and code changes will have to be done in another branch since I will delete my own branch soon (since it got merged), it's probably better if you create your own branch with your own fixes. I don't have any project to test that with yet, so you would be the best person to handle that.

For your problem, you could possibly save all open templates into an array and re-use the content of the array if you need to.

**Comment by SatanEnglish** [comment]
@ghiscoding

Issue is there isn't anything to hook into that says the item is scrolled off screen that I can find.

**Comment by SatanEnglish** [comment]
@6pac @ghiscoding  
Do you guys know a way to check the scroll direction in the onScroll event?

I've got some changes for the current version and I'd like to make it more efficient if possible.

Basically I am currently saving the state of the view as it gets scrolled out of view range.
Only issue now is that I don't know if the top or bottom is going off screen so checking for both.

If I know the direction I can just save the relevant one.

I'll try and make a new PR for this once I'm happy with it working on my system

**Comment by 6pac** [comment]
I've been staying out of this one, but I'd comment that IMO it's part of a broader data strategy for the grid and best not built int to the plugin. Normally I have buttons to save data, but here if it can be scrolled it needs any changes to be immediately saved to the backing local data store. That's probably best achieved with an event bound to a CSS class that's applied to all data controls.

Usually I'd use a single data store (maybe a DataView) and pull display data for the grid out of a limited subset of columns, then use all the data for the detail level editing. Having a separate dataset complicates things significantly, but if it's part of the use case, better to allow formal handling of a second DataView than to handcraft something.

Feel free to ignore this, just my 2c.

**Comment by 6pac** [comment]
Something like that. Not sure how using scrolling as the trigger would affect performance though, that's the kind of thing that the postRender event is used for.  
I was thinking more of an onKeyPress or onClick event, so that any change to control  data could be saved as it was made. Then you can be sure that anything scrolled offscreen is updated without having to worry about the actual scrolling process.

**Comment by SatanEnglish** [comment]
@6pac is there there an on before row cache row remove event?
They must be getting removed in the core somewhere would having an event to hook into be the better way to go?
Most of the time its a quick check !item._collapsed.
So an event would be a quick check and release case unless all DetailView are open.

**Comment by SatanEnglish** [comment]
@ghiscoding
Have a look at the slick.rowdetaiilsView.js

HandleScroll function.

I'm at every point of the scroll determining if the top or bottom item is an open panel and if it is saving the data.

I don't actually need to collapse it at all as it's just like a formater it's loaded back in when it comes into view.

There is a bit of an issue if the view port of the slickgrid is smaller than the expanded view to when scrolling back into view so be carefull.

Have a look at commit 82a9e95.

If you need some other information about it please let me know.

Also if you find a nicer way to do some of this stuff please update the main branch and let me know.

Thanks

**Comment by ghiscoding** [comment]
@SatanEnglish 
Thanks for pointing me to that commit, it helped me in finding a way to handle my own problems with the plugin which are different than yours. In my case, since I use frameworks (Aurelia/Angular) that have their own way of creating templates dynamically, I can't just save the template data like you do. I have to instead call the framework to re-render the template when necessary. With that knowledge, when I get out of the cached rendered rows and if I want to keep that opened template, I would have to re-render the template (just like you call the `saveDetailView`). 

So because I cannot use your `saveDetailView` implementation, I think your `onScroll` is overkill in my case since it will never be useful in my situation. And so, I think the `onScroll` should be optional through a flag (which can be set to True by default, so that it won't break your code but I could disable it on my side and use my own `onScroll`). 

As for the `onScroll` itself to check for when to call the `saveDetailView` (or re-render in my case), I think that I found a much simpler way of knowing when it's out of cached window. You should **not** use the `getItemByIdx()` on every scroll, that is a huge performance hit. You should instead use it only when you are ready to save it. As for the code to know when you reached out of the cache window, you can use this (I tried it and it works good on my side).
```javascript
var renderedRange = _grid.getRenderedRange() || {};

// calculate how many rows are shown on screen
var visibleRenderedCellCount = renderedRange.bottom - renderedRange.top - _options.minRowBuffer; 

function handleScroll(e, args) {
      var renderedRange = _grid.getRenderedRange();
      if ((renderedRange.bottom - _options.minRowBuffer) > (visibleRenderedCellCount * 2)) {
        // do your getItemByIdx() here and saveDetailView
      }
}
```

Finally I noticed that there are a lot of code that could be cleaned up, I might create a PR to address a few things that bothers me
- mentioned on top, the `onScroll` should be optional under a flag (that is an easy one)
- the `handleScroll` should be simplified (see the code I've posted on top)
- `collapseAll` method is exposed (public) but `collapseItem` (private) is not but could be useful, again easy to do.
- `itemDetail` includes a bunch of properties related to the detail view and this is not good, the object data context should be clean and without any extra properties. For example, if I want to take this object `itemDetail` and save it as it is, I would have properties like (`_collapsed`, `_parent`, `_detailContent`, ...) that is so bad.
   - to address this, I think all these info should be in a separate property (like `detailViewInfo` or something). However this would be a breaking change for anyone using these properties (like `_collapsed` which is often useful) 

I'll probably start a branch to test these and create a PR eventually. @SatanEnglish I will request your feedback soon enough as I know you are the biggest user of this plugin
