### ISSUE TITLE
Multi-Column Sort no way of knowing when sort is cleared - slick.grid issue

### ISSUE THREAD

**Issue by smurphdog** [6pac/SlickGrid#211]
With a Change back in December 19, 2016 a bug was introduced prohibiting notification of the onSort event when the array to sort had zero length. This prohibits knowing when all of the sorted columns have been removed and the grid is essentially not sorted. Now there is no way of knowing that there are no columns currently selected for sorting. If the "If" check "if (sortColumns.length > 0) { " is removed from slick.grid, consumers will know when the grid is no longer sorted.

**Comment by 6pac** [comment]
OK, good call.  Because the whole thing is wrapped in 

     $headers.click(function (e) {

it was tempting to conclude that there would always be a clicked header and therefore sort column. However, the addition of tri-state sorting around the same time as these changes were made allows a column click to remove the sorting on that column.
 I have replaced the 'If' block with the following code, to avoid errors from trying to pass ```sortColumns[0]```. The ```map`` function in the multi-column branch should be OK.

         if (!options.multiColumnSort) {
            trigger(self.onSort, {
              multiColumnSort: false,
              sortCol: (sortColumns.length > 0 ? column : null),
              sortAsc: (sortColumns.length > 0 ? sortColumns[0].sortAsc : true),
              grid: self}, e);
          } else {
            trigger(self.onSort, {
              multiColumnSort: true,
              sortCols: $.map(sortColumns, function(col) {
                return {sortCol: columns[getColumnIndex(col.columnId)], sortAsc: col.sortAsc };
              }),
              grid: self}, e);
          }
        }

This does have the possibility that the single column sort case ```sortCol``` will be null and may cause an error in code that worked previously, but this was always a possibility with tristate sorting, and previous behaviour was actually incorrect.
