### ISSUE TITLE
Grid content disappear when dragging scrollbar on big data sets

### ISSUE THREAD

**Issue by JoeOM** [6pac/SlickGrid#219]
Hi

I love SlickGrid, but unfortunately, the content disappears when you drag the scrollbar adjuster with big datasets. This does not happen in a few other grids which make me think it can also be done in SlickGrid.

DevExpress React grid, for example, does not seem to have this issue...

https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/

Could the community maybe look into this?

Thank you very much guys!

**Comment by 6pac** [comment]
Yeah, I think we've talked about some kind of rate limiting before. I think the events just pile up, and most could be discarded.

The difference between those grids and this one, though, is that they're professionally developed, this one is purely volunteer, and we're all quite busy!

So I'll put this on the 'todo' list. I'm trying to get a web site together for SlickGrid, partly to marshal the community more effectively and make use of those valuable people who might have time to just play with things like this and come up with a viable solution. Sorry I can't do better.

**Comment by ghiscoding** [comment]
@6pac 
while converting SlickGrid to TypeScript I found that the reason why we always see white section when scrolling large dataset is because of this scroll throttling shown below

https://github.com/6pac/SlickGrid/blob/4b06690a2d5d225537deaec943b408bcd555256c/slick.grid.js#L237

which is used in the action throttle

https://github.com/6pac/SlickGrid/blob/4b06690a2d5d225537deaec943b408bcd555256c/slick.grid.js#L4464-L4468

it looks like you were the person who made this change via this commit
https://github.com/6pac/SlickGrid/commit/93f043fa587e377462d2fe0fa7525ff9f1b3f3ef

do you know why we have to use `50` as a throttling? perhaps we could keep the 50 as default but also provide a grid option? with a grid option we could let the user try for themselves.

**Comment by 6pac** [comment]
No recollection of doing this at all (and no commend in the commit :-/ ). Happy with a settable delay and a change to the default.

**Comment by ghiscoding** [comment]
ok I'll add it to the TypeScript version only for now, if we ever have other fixes to commit on current version then I could backport it if need be.

**Comment by ghiscoding** [comment]
improvements were made in v5.0, see [SlickGrid 5.0 Announcement and Migration](https://github.com/6pac/SlickGrid/wiki/Major-version-5.0-%E2%80%90-ES6-ESM-and-TypeScript-Support)
