### ISSUE TITLE
Conditional Row Background does not work with Grouping

### ISSUE THREAD

**Issue by nzhtrtlc** [6pac/SlickGrid#235]
Hi, i am trying to change background of row by the value. I can do that.
But when i do that it does not work with grouping. Here is the code how i can set the background of row.

>  this.dataView.getItemMetadata = (row) => {
          const data = this.dataView.getItem(row);
         console.log(data);
         // if(data.hasOwnProperty('myProperty'){ // code })
         return { 'cssClasses': 'highlight' };
      };

With this code i commented out my condition so all rows has background color.
![image](https://user-images.githubusercontent.com/17534778/39421439-b84e91ce-4c71-11e8-9c3a-db1fb9501677.png)

But when i group some column it looks like this.
![image](https://user-images.githubusercontent.com/17534778/39421457-d16013d6-4c71-11e8-8dae-c2e212754ac8.png)

How can i make this work with all the other features, specially grouping ?

Thanks.

**Comment by 6pac** [comment]
It looks like the row background code is actually working. 
Are you sure this isn't just a problem with the grouping? Have you started with the grouping example and added your background code to see if it works there?
This kind of question should be posted on StackOverflow. The Issues area is for bugs and enhancements only.

**Comment by nzhtrtlc** [comment]
@6pac Grouping function works as expected if i remove this code

`      this.dataView.getItemMetadata = (row) => {
         //const data = this.dataView.getItem(row);
         //return { 'cssClasses': 'highlight' };
      };`

I think grouping is not working if i set *getItemMetadata* function into dataView.
So you say its not a bug ? Then what is it ? How can set my row bg color without any problems ?

**Comment by 6pac** [comment]
Possibly. You're using the drag-to-group plugin as well, which I don't fully trust.

If you want assistance, you need to:
1) start with the simplest example from the repo that will reproduce your problem. I'd use the grouping one without the drag function to start.
2) Add your background code to it and see if it works
If it works, you track it back to your example one step at a time, if not, post the link to the example and the mods you made to the example

There are a lot more people monitoring StackOverflow. The best policy is to query the problem there first. If it turns out to be a bug, then post the specific bug here.

**Comment by nzhtrtlc** [comment]
@6pac Okay i will write the result here after i done with the steps you wrote.

**Comment by nzhtrtlc** [comment]
https://drive.google.com/file/d/1nQ_NB4-2kTlRpRlKAlJvNDIIBdNGrDwD/view

@6pac I uploaded a video, i hope it is clear to understand.

**Comment by 6pac** [comment]
Awesome. That definitely should be in the docs. I might even create a new example specifically to demonstrate this.
