### ISSUE TITLE
NPM sometime download version 2.4.0 that doesn't exist

### ISSUE THREAD

**Issue by ghiscoding** [6pac/SlickGrid#245]
@6pac 
Have you created a version `2.4.0` by mistake in the past? I was re-downloading my NPM packages today and had something broken, after investigating I saw that the `package.json` was showing as version `2.4.0` and if I search on internet, it looks like there was a version [2.4.0](https://www.npmjs.com/package/slickgrid/v/2.4.0) at some point in time. If so, you might have to do an [npm unpublish](https://docs.npmjs.com/cli/unpublish) to remove it, else this issue might come back. Looks like it was published 2 months ago

If we go on NPM and do a `npm install slickgrid` it will always take highest version number, which is `2.4.0` but that is not the most recent version. That version also happened to have the `function getHeaderColumn(columnIdOrIdx)` bug which is not a good showcase of the lib :S

![slick2 4](https://user-images.githubusercontent.com/643976/40260463-c4704442-5ac8-11e8-8e1a-5beb74d2416a.png)

**Comment by 6pac** [comment]
That was an accidental publish while I was testing the version release tool.  
I had a conversation with the folks at NPM and they steadfastly refuse to unpublish it since it's more than 24 hours old (attempting to do so via the command line tell you to contact them).

So I've deprecated it. Once the frozen-column changes are in place, I think we'll go to 2.4.x anyway.
