### ISSUE TITLE
RowDetailView handling filter row counts

### ISSUE THREAD

**Issue by SatanEnglish** [6pac/SlickGrid#254]
@6pac @ghiscoding 

New issue working around at the moment.

Need to get the length of the showed rows.
Trying to do this without changing underlining core stuff again...

Inside of slick.dataview.js I can see that the getLength method returns the rows.length.
These are only the visable rows.

I'm wanting to get to that rows object but it turns out it's not the same one that is exposed. 

e.g. 
_dataView().rows gives me all the rows even the hidden ones;

Is there a way to get to these objects?

**Comment by SatanEnglish** [comment]
onRowCountChanged = function () {
                var rows = 0;
                for (var i = 0, l = grid().getDataLength(); i < l; i++) {
                    // Check for expanded row data
                    if (!grid().getDataItem(i)._parent) { rows++; }
                }
                window.setRowCount(rows);
            };

This works for now but it's a little nasty

**Comment by ghiscoding** [comment]
So unless I am mistaking, we already have the `getExpandedRows()` method that returns the expanded rows. If that is not what you were looking for then please provide more details but for now I'll go ahead and close the issue. 

Note that a lot changed since this issue was opened, our whole code structure changed (we removed jQuery/jQueryUI and we migrated to TypeScript).
