### ISSUE TITLE
autosizeColumns should trigger onColumnsResized

### ISSUE THREAD

**Issue by vlsi** [6pac/SlickGrid#261]
subj.

I can easily provide a PR, however could you please merge https://github.com/6pac/SlickGrid/pull/260 first?

**Comment by ghiscoding** [comment]
I'm not sure this is ideal though, in my case I use the `onColumnsResized` to keep track of the resizes in Local Storage (a Grid State service) and when I create the grid I always call an `autosizeColumns` which (if we follow your logic) would then call a resize and change my Grid State, but that isn't true since it's on grid creation. However I can probably do some extra checks to avoid calling my Grid State but we have to know about these potential side effects, perhaps what we could do is add a `caller` property to mention who triggered it, something like this `trigger(self.onColumnsResized, { grid: self, caller: 'autosizeColumns' });`

**Comment by vlsi** [comment]
I see.
My usecase is to add a search field into column header as follows: 
<img width="896" alt="2018-07-19 19 18 58" src="https://user-images.githubusercontent.com/213894/42956450-a7bb756a-8b88-11e8-9187-0bf3496c548a.png">

I use `onColumnsResized` to update position of the search field.

PS. I've just migrated from very old mleibman's version, so I've no idea if "header plugin" could be better here or not.

**Comment by ghiscoding** [comment]
We can wait and see what @6pac would reply, but I would be ok to trigger a column changed if we do add a `caller` property as mention in my previous post

> However I can probably do some extra checks to avoid calling my Grid State but we have to know about these potential side effects, perhaps what we could do is add a `caller` property to mention who triggered it, something like this `trigger(self.onColumnsResized, { grid: self, caller: 'autosizeColumns' });`

**Comment by 6pac** [comment]
I've always interpreted ```onColumnsResized ``` as meaning that the user has manually resized a column. I can see two ways forward, either

1) a new 'onAutoResize' event
2) perhaps a 'TriggerColumnsResizedOnAutoResize' default and add the caller param as suggested by @ghiscoding .

I suspect option(1)  is cleaner.

**Comment by vlsi** [comment]
`onAutosizeColumns` makes sense

**Comment by 6pac** [comment]
Released.
