### ISSUE TITLE
Inconsistency between sortable and non-sortable columns

### ISSUE THREAD

**Issue by andreasmueller92** [6pac/SlickGrid#267]
When creating a grid with some sortable and some non-sortable columns, headers look a bit weird, as some of them have a bigger padding on the left than others.

This is caused by the fact that the span holding the glyph-icon that is indicating a sorted column is always shown.

My suggestion would be to only show it when an actual sorting happens.

This will also prevent headers of unsorted columns from moving when disabling sorting programatically.

**Comment by 6pac** [comment]
Yeah, this has been dodgy for a while. The reason I often leave these things is that most developers have their own scheme they want to impose. I am just in the process of tidying up the same issue, so I'll release something in the next few days. @ghiscoding right aligns the icon in the column. I recall choosing to always show it because otherwise displaying it on sort can cause rearranging of elements in the header. I suppose a proper boxing with overflow:hidden could cure that.

**Comment by ghiscoding** [comment]
@6pac 
on your next change for this, you can create a PR make me a reviewer. I could pull your code and give it a try in my libs and see if anything breaks. I would rather try before it's merged to master, if possible. Thanks

**Comment by 6pac** [comment]
No probs, I know I've broken your branch in the past :-<
This is quite a tricky one, as it's CSS related and everyone seems to tweak it a bit. There's a distinct possibility *any* change will break a significant number of deployments.

**Comment by ghiscoding** [comment]
This should be fixed in v5.0 with the new Alpine Theme

Single Sort
![image](https://github.com/6pac/SlickGrid/assets/643976/f8b9f864-fbd1-43eb-8d8c-275284daff4d)

Multi-Sort

![image](https://github.com/6pac/SlickGrid/assets/643976/311909ea-7d45-4f11-9bf5-45906d40c97d)
