### ISSUE TITLE
Scrolling drops attributes

### ISSUE THREAD

**Issue by ingodjango** [6pac/SlickGrid#296]
I'm adding attributes to the cell, to add tooltips in that way:
```
function add_comments_as_tooltips(cell_node, comment, row)
{
  
  if (cell_node != undefined)
  {
    var placement = "right";
    cell_node.title = comment;
    cell_node.setAttribute("data-toggle","tooltip");
    var viewport = grid.getViewport();
    if (!cell_node.nextSibling || viewport.top == row)
    {
      placement = "bottom";
    }
    cell_node.setAttribute("data-placement", placement)
    
    $('[data-toggle="tooltip"]').tooltip()
  }
}

```
Works but as soon as I scroll up and down and the rows and cells get newly rendered the added attributes (data) get dropped.

Any idea how to tackle that?

Thanks,
Ingo

**Comment by 6pac** [comment]
Either build this into the cell formatter, or use ```onBeforeAppendCell```

**Comment by ingodjango** [comment]
Thanks, works eith `onBeforeAppendCell` but that also means I have to keep the attributes/events in another cache or maybe retrive and set them again.

**Comment by 6pac** [comment]
Rather than trying to set attributes for all the rows, slickgrid is best suited to processing the attributes for just the few rows that are being displayed. If this is slowing down the grid too much, you can always use the column ```asyncPostRender``` property, that's what it's for: https://github.com/6pac/SlickGrid/wiki/Column-Options
