### ISSUE TITLE
Refiltering on grouping 

### ISSUE THREAD

**Issue by Narrenschyff** [6pac/SlickGrid#33]
Hi,

Apologies if this question sounds stupid or out of place, I am just trying to optimise some code I am working on involving grouping and filtering. I have looked at the example here http://mleibman.github.io/SlickGrid/examples/example-grouping,

however it is a bit unclear to me why everytime we call dataView.setGrouping() we need to perform filtering again in dataVIew.refresh() -> .. -> getFilteredAndPagedItems(items) instead of accessing the already filtered items through the global var filteredItems which would spare the filtering call?

I have a feeling I am overlooking something and I would appreciate your help.

Many thanks,
Yulia

**Comment by 6pac** [comment]
Hi Yulia, and sorry this slipped through without reply. You might want to try StackOverflow which is the official place for questions.

You are correct that the re-filtering in this example is not optimal. I suppose the issue is that filtering may have changed and that there would need to be a 're-filter' flag to indicate to do the filtering again. 
As I've said elsewhere in these forums, SlickGrid is more like a toolkit than a final product, and this is because people's use cases vary so widely, what is an optimisation for one person could cause trouble for another. It's kind of expected that there will be a bit of tweaking going on.
So you could probably add such a flag without too much trouble. I may get around to doing that one day. There is also an 'optimising DataView' example that has some refinements of a similar nature.

Ben
