### ISSUE TITLE
Editor: Ctrl+v paste is happening on non editable cells 

### ISSUE THREAD

**Issue by sreenithalbhat** [6pac/SlickGrid#369]
Also i want to keep a column read only in editor and when i paste using Ctrl + V its getting pasted in that column too. ie: there are cells that are not editable but it still paste values

Can you please help how to prevent from pasting in that particular column?

**Comment by 6pac** [comment]
firstly, this repo is pretty much dead. Please use https://github.com/6pac/SlickGrid and see if there's been a fix for this, otherwise post an issue there.

**Comment by ghiscoding** [comment]
@6pac he is already posting the question in your fork lol

This question came from my repo, this [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/171#issuecomment-488676112), it's actually related to the Excel Copy Manager, in this [Example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) user can paste value even if the cell is editable or not, I told him to open the ticket here because I think it's a problem with `cellexternalcopymanager`. It paste regardless of the type of field, editors or not, basically read only or not. Like in the example, the first column is the Id and is not editable, but you can still paste on top of it, I think it shouldn't

**Comment by 6pac** [comment]
whoops, got mixed up! there was a post here and in the original repo...

will have a look over the weekend. i seem to recall something similar recently, anyway will check.

**Comment by ghiscoding** [comment]
Having another thought on the subject, this functionality should be an extra flag that we could pass as an option to the `cellexternalcopymanager` plugin. Basically we wouldn't want to break people's code, so a flag is probably best, to enable/disable this functionality of pasting to anything or only cell with editors.

**Comment by 6pac** [comment]
@sreenithalbhat did you fix the issue for just give up waiting? Sorry, this has been on my list for a while, but it has not made it to the top yet!

**Comment by ybarbaria** [comment]
Hello @6pac did you add something regarding this option?

**Comment by 6pac** [comment]
Not yet ... maybe next week!
