### ISSUE TITLE
feature request : onPasteComplete 

### ISSUE THREAD

**Issue by reteid** [6pac/SlickGrid#373]
It would be great if there was an 'onPasteComplete' event that could be subscribed to.

at the moment when pasting multiple cells and rows,  onCellChange runs for each cell , but if I detect invalid data, I cant undo the paste as the 'oldValues' object in CellExternalCopyManager is only complete after all the executions of 'onCellChange' .

Ideally it would be great to call the paste-undo ,if necessary, in the 'onPasteComplete' event

**Comment by reteid** [comment]
PS I did attempt to create the event with trigger/notify/subscribe and extend "onPasteComplete": new Slick.Event() , but without success

**Comment by ghiscoding** [comment]
@reteid 
I know this is an old issue but could you please provide more details, I imagine this is for one of the plugin, if so which one? We're cleaning up old issues since the project structure changed a lot in the past year because we modernized the project (removed jQuery/jQueryUI, migrated to TypeScript), so in short if no detail is provided soon then we will close this issue. If you do provide details then I could potentially look into it.

**Comment by reteid** [comment]
Feel free to close this
