### ISSUE TITLE
Add class to row that has its panel open

### ISSUE THREAD

**Issue by MrMoronIV** [6pac/SlickGrid#379]
Following this example: http://6pac.github.io/SlickGrid/examples/example16-row-detail.html

Can a class be set to the row that has its panel open? Guess this should be default behavior of this plugin?

**Comment by ghiscoding** [comment]
All the documentation is directly inside the [Row Detail Plugin](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js#L11) and has a few CSS properties you can change. Please consult it and it will probably answer all your questions

**Comment by MrMoronIV** [comment]
As far as I can tell it only affects the switch in the first column of the row and not the row itself, hence this question :)

**Comment by SatanEnglish** [comment]
expandedClass Think this is the options your looking for though this may be one div deeper than you need.

Alternatively you could after the detailView is opened get from the returned data in the function the _parent which would allow you to get the row that you need to put the class on.

Hope this helps

**Comment by MrMoronIV** [comment]
`expandedClass ` just adds another class to the arrow in the first column when it is expanded, it already gets the class `expanded` so yeah, it seems a bit useless to have the option to add another one.

Didn't know about the `_parent` option, did however already create a workaround with a jquery selector.

My best guess is that adding a class to the row when expanded is very little work for the maintainer of the plugin and would be very useful for others as well.

**Comment by ghiscoding** [comment]
The Row Detail plugin does not, and should not, modify the parent row. So what you are requesting will not be done in the Row Detail Plugin itself. 

However, you can do it within your own code by adding `cssClasses` via the SlickGrid Item Metadata. You can read this Stack Overflow [answer](https://stackoverflow.com/questions/19887575/changing-background-color-of-a-specific-row-in-slickgrid/19985148#19985148) on how to do that. You can add a css class via the `onBeforeRowDetailToggle` or `onAfterRowDetailToggle` triggers. 

Closing since there's nothing to change in the lib neither the plugin
