### ISSUE TITLE
Missing LICENSE file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [6pac/SlickGrid#390]
I found 2 license-related problems:

- [ ] missing `LICENSE` file at top of repo (currently named `MIT-LICENSE.txt`)
- [ ] missing `LICENSE` file in the release tarball (under https://registry.npmjs.org/)

**Comment by 6pac** [comment]
Can you clarify these? There is a license file in the repo, and these look like autogenerated messages. We may not interested in conforming to someone's notion of how the repo should look.

**Comment by ericsnowcurrently** [comment]
First of all, thanks for maintaining a project that meets a need in the project I work on!

Looking back at my original message I can see how the context and intent were unclear.  There isn't anything wrong.  The license file is just unconventionally named.  Sorry I wasn't more clear.  I'm certainly not in a position to tell you how you need to do things. :)

Just to clarify, the problem for us was not finding a file named "LICENSE" in this repo or in the corresponding tarball we got from https://registry.npmjs.org/.  We look for a file named "LICENSE" since that is the convention.  (I'm not aware of any standard or requirement for naming the license file.)  Out of all our dependencies, this project is the only one that has a license file but it isn't named "LICENSE".  (That is not bad, just unexpected.)  So I figured I'd let you know in case it mattered to you. :)  Again, I apologize for being unclear.

FYI, in the project I work on we copy all the licenses for our dependencies into a single file, which is what we distribute in our releases.  We have hundreds of dependencies, so the task is mostly automated.  The tool looks for a top-level file named "LICENSE" (since that is the conventional name) both in the repo identified by the npm metadata and in the tarball we get from npm.  If that doesn't work then we do it manually, which is how I found your license in a file by an unexpected name.  Interestingly, aside from this project the only problem we ever run into with dependency licenses is where they do not have a license file at all!

At this point we already manually added your license to the file in our project, so it doesn't make a difference for us if you change the file name or not.  I just figured you might like to know the filename is unconventional.  Thanks again!

**Comment by vlsi** [comment]
@6pac , just to clarify:
MIT license is very permissive (which is good), however it requires re-distributions to keep copyright references:

> MIT license: The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software

It is really complicated to keep the copyright notice since it is not clear what is the proper notice for slickgrid 2.4.10 or whatever version.

As ericsnowcurrently says, it is so much easier to keep the copyright notice in case slickgrid distribution includes proper LICENSE file.

I would agree with ericsnowcurrently that "convention" names are `LICENSE` and `NOTICE`.

I have recently created similar issues with "please include LICENSE file to the distribution": https://github.com/apache/jmeter/pull/469#issuecomment-502834212

> ericsnowcurrently: At this point we already manually added your license to the file in our project,
> so it doesn't make a difference for us if you change the file name or not

Technically speaking, that is a workaround only since the copyright notice of further slickgrid versions might change, so one would have to manually inspect if the license/copyright notice changes on each and every upgrade. Bundling LICENSE does help there.

> ericsnowcurrently: missing LICENSE file at top of repo (currently named MIT-LICENSE.txt)

@ericsnowcurrently , the source code layout does not matter much. Note: one can't really just use a license file from a Git branch since there's no relation between slickgrid artifact and the license file under Git control. However I would agree `LICENSE` or `LICENSE.txt` are more expected names than `MIT-LICENSE.txt`

**Comment by vlsi** [comment]
> ericsnowcurrently: FYI, in the project I work on we copy all the licenses for our dependencies into a single file

@ericsnowcurrently , are you using a "standard" or "conventional" format for the resulting file format?
Can you provide a sample if that is possible?

**Comment by 6pac** [comment]
Thanks for raising this issue, I wan't aware of these conventions. If I took a critical tone, it's just because there's been criticism in the past because we're not conforming to extended requirements for 'Package Manager X', for which support was often added as an afterthought by a contributor. I've always viewed SlickGrid as a toolkit rather than a finished product, so I've never been keen about providing a fully packages deployment.

Anyway, always happy for some friendly advice!

**Comment by ericsnowcurrently** [comment]
@vlsi, I don't know what the format is.  The project is open-source, so [take a look](https://github.com/microsoft/vscode-python/blob/master/ThirdPartyNotices-Distribution.txt).  If you think there's a problem then please open an issue on our issue tracker and feel free to mention me there.

Regardless, thanks for clarifying what I said. :)

**Comment by ghiscoding** [comment]
Hello, @ericsnowcurrently @vlsi @6pac 

I raised a PR #396 to address this issue, a simple rename to `LICENSE` which is more the standard. I believe this addresses the issue. If something else is required, please speak up now. Thanks
