### ISSUE TITLE
Last row cut off from bottom of grid

### ISSUE THREAD

**Issue by alexsielicki** [6pac/SlickGrid#400]
Since version 2.4.10, the last row is cut off from the bottom of the grid. In version 2.4.9, I can scroll down to the last row. In version 2.4.10, I can only scroll down to the second to last row.

**Comment by ghiscoding** [comment]
We are aware of the issue and it was fixed in this [commit](https://github.com/6pac/SlickGrid/commit/ceded1b737764394e8c58965fe88400c550c722b), however this was not yet released under a new version yet. There a couple of other things that we have to look into before releasing another version. In the meantime, we suggest  you to stick with `2.4.9` until we release `2.4.11` which will contain the fix.

**Comment by alexsielicki** [comment]
Thanks, we'll wait until 2.4.11 and use 2.4.9 for now.

**Comment by ghiscoding** [comment]
A new version `2.4.11` can you try it out and see if that fixes the issue

**Comment by alexsielicki** [comment]
This seems to have fixed the issue for us. Thanks!

**Comment by ghiscoding** [comment]
Good to hear, please close the issue if this is fixed 😄
