### ISSUE TITLE
Does this fork support TypeScript?

### ISSUE THREAD

**Issue by TANZAME** [6pac/SlickGrid#404]
well,it's a nice table component actually,but unfortunately it seems not suppot typescript.so Does it will support the TypeScript?

**Comment by TANZAME** [comment]
i mean, Does it will rewrite by TypeScript

**Comment by ghiscoding** [comment]
Not at this point, unless you want to go and start that project then contribute to the lib.

**Comment by TANZAME** [comment]
Thank you, so much for your help.

**Comment by ghiscoding** [comment]
@TANZAME 
Another update since you posted this question, I created a 3rd lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) on top of SlickGrid (it's a wrapper on top of the great `6pac/SlickGrid` fork), this new lib is framework agnostic it is all written in TypeScript (it is fully typed, the entire SlickGrid, DataView have type defined). Since it is framework agnostic, you can use it in any framework or even plain TypeScript/JavaScript if you wish, for example all the [Slickgrid-Universal - demos](which means that it can be used in any framework or even plain TypeScript/JavaScript) are written in plain TypeScript and WebPack. This new lib was created because we now use it in a Salesforce environment which requires plain ES6 JS (which is available after a build by the `dist` folder).

So if you want TypeScript support, I strongly suggest you to take a look at my new lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) 

With that saying, could we close your issue?
Cheers

**Comment by TANZAME** [comment]
@ghiscoding 
actually it's not an issue,it is a advice,I think.
so you should close this issue as your with.
thanks.

**Comment by ghiscoding** [comment]
Better late than never, the project is being rewritten in TypeScript and will be eventually release as v5.0 (see [Roadmap to v5](https://github.com/6pac/SlickGrid/discussions/807)

**Comment by ghiscoding** [comment]
Revisiting issues mentioning TypeScript... 

We migrated to TypeScript in v5.0 and we now use esbuild to build 3 different build targets (`iife`, `cjs` & `esm`) which officially closes this issue, see [SlickGrid 5.0 Announcement & Migration](https://github.com/6pac/SlickGrid/wiki/Major-version-5.0-%E2%80%90-ES6-ESM-and-TypeScript-Support) for more info
