### ISSUE TITLE
Feature Request: footerCssClass per column

### ISSUE THREAD

**Issue by ghost** [6pac/SlickGrid#421]
I apologize if this is a bit excessive, but seeing as there is the option to set a headerCssClass on individual columns, it would be nice to have a footerCssClass as well to primarily allow text alignment and other small styling enhancements on a column-by-column basis for footer rows.

I have this in a local fork and would be happy to clean it up and contribute it if there is interest in having this upstream.

**Comment by 6pac** [comment]
sure, that makes sense.

**Comment by ghiscoding** [comment]
We're cleaning up old issues since the project structure changed a lot in the past year because we modernized the project (removed jQuery/jQueryUI, migrated to TypeScript), so in short if no detail is provided soon then we will close this issue. I could potentially look into this issue if more details are provided, thank you

**Comment by ghiscoding** [comment]
closing since no feedback provided, we can work on it if more info is provided in the future. Thank you
