### ISSUE TITLE
Slick.AutoWidthStrategy => Object.freeze: argument is not an Object

### ISSUE THREAD

**Issue by zoltan-boros** [6pac/SlickGrid#435]
On loading [example4-model.html](http://6pac.github.io/SlickGrid/examples/example4-model.html) in IE 11 the below error raises:
```
SCRIPT5007: Object.freeze: argument is not an Object
slick.core.js (90,5)
```
The line referenced in the error message is:
```javascript
Object.freeze(Slick.AutoWidthStrategy);
```
Screenshot:

![bug-Slick AutoWidthStrategy_is_undefined](https://user-images.githubusercontent.com/11786418/64939025-1e666d80-d860-11e9-9d7b-e4ed695ee570.png)

The issue is reproducible in release 2.4.13 and in the current master branch (d71fa57f3795475a9db46af719e83e3d2aaaf184) as well.

Suspected cause:

In e3d21ba0 commit `AutoWidthStrategy` has been renamed/removed in `slick.core.js`, therefore the `Object.freeze(Slick.AutoWidthStrategy);` line causes error in IE 11.

**Comment by zoltan-boros** [comment]
I would fix this issue, however I cannot create branch.
Is it restricted?

**Comment by ghiscoding** [comment]
I'm not sure you can create a branch directly in GitHub but it works if you create a branch locally and then push the code. Just make sure to create the PR (Pull Request) against the 6pac repo and not the original mleibman repo since you'll have tons of conflicts.

**Comment by zoltan-boros** [comment]
Thank you for your help.
I tried to carry out your suggestion, however, for some reason my push command gets refused with "403 permision denied" feedback.

**Comment by ghiscoding** [comment]
You usually get this message when you try to push to the `master` branch, which is not allwed. Have you forked the repo to your name and create a commit from your local repo first? My role is a bit different since I'm a `contributor`, so I can't really try on my side. I found this [article](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) which might help. Give that a try and if that doesn't work out then let us know and we might replicate your code change.

![image](https://user-images.githubusercontent.com/643976/64987494-4ae9ac00-d897-11e9-9b35-e4365e43b012.png)

**Comment by 6pac** [comment]
Thanks for raising this @zoltan-boros, I have pushed a fix. This was a straight out error, I have actually removed the freeze statements altogether. It's a pattern I use in other projects, but it's not used elsewhere in Slickgrid.

It is worth learning how to create a PR against the repo as @ghiscoding has suggested above.

**Comment by zoltan-boros** [comment]
Thank you for the prompt action and support. :)
