### ISSUE TITLE
how to check the API doc for 2.1 version?

### ISSUE THREAD

**Issue by JasonRao** [6pac/SlickGrid#480]

**Comment by 6pac** [comment]
Sorry, what do you mean by 'API doc'? The 2.1 version would be in the MLeibman repo.

**Comment by JasonRao** [comment]
Hello 6pac,
Below is the API doc fot the latest version of SlickGrid, i can't find the for version 2.1
https://github.com/6pac/SlickGrid/wiki/API-Reference

**Comment by 6pac** [comment]
Ah, OK. The wiki in the MLeibman repo would be what you're after. 
Be aware that we are pretty slack about updating the wiki docs, so there may not be a good coverage of new features in the current wiki. We're just too busy! If you want to update the document with new features, please do. The example are where most of the documentation is concentrated at the moment, so if there is a new feature we will generally make a new example or incorporate it into an existing one.

**Comment by ghiscoding** [comment]
like @6pac mentioned, we don't really update Wikis but we have many [Examples](https://github.com/6pac/SlickGrid/wiki/Examples) covering all features, there's also [Stack Overflow](https://stackoverflow.com/questions/tagged/slickgrid) that you can search which has many SlickGrid questions and answer. 

Closing since I don't think there's much more we can do
