### ISSUE TITLE
queuePostProcessedRowForCleanup is never called

### ISSUE THREAD

**Issue by haqk** [6pac/SlickGrid#483]
asyncPostRenderCleanup does not work. queuePostProcessedRowForCleanup is defined but not called anywhere. It seems all calls to this function was removed since version 2.4.0.

**Comment by ghiscoding** [comment]
It's quite possible since version `2.4.0` introduced the Freezing (pinned) Rows/Columns and that was quite a lot of code to merge from the `X-SlickGrid` with the `6pac` fork. We tested as much as we could but certain things like this don't really show up in the UI and we most probably forgot to test that portion (most of our tests at the time were mostly visual).

Looking at previous version tag `2.3.23`, it seems to be called at 2 different places [here](https://github.com/6pac/SlickGrid/blob/2.3.23/slick.grid.js#L1842) and [here](https://github.com/6pac/SlickGrid/blob/2.3.23/slick.grid.js#L2637)

It would be really great if you could contribute and do a Pull Request with any fixes. I personally rarely, if ever, really use the `asyncPost` so I would rather have someone else who uses the feature to do the fix. Thanks for your help

**Comment by haqk** [comment]
Sure. I will give it a shot.

**Comment by ghiscoding** [comment]
@haqk 
I created a PR to add the missing piece of code, but I don't know how to test this all out. If you can test it, that would be great, else it might never be merged. Thanks

**Comment by haqk** [comment]
Apologies, I have yet to learn enough about git to do a PR. In regards to the test, Example 10 located at https://6pac.github.io/SlickGrid/examples/example10a-async-post-render-cleanup.html still has a reference to asyncPostRenderCleanup. Function cleanupSparkline wasn't getting called. I'm guessing now it should. Thanks.

**Comment by ghiscoding** [comment]
@haqk now it does, I posted a print screen in the PR #495 but I'm not sure if there's anything else to test.

**Comment by haqk** [comment]
@ghiscoding My use case is similar to example 10 and does not go any further than cleaning up after manipulation the DOM node directly. Aside from investigating this bug, my knowledge of SlickGrid code is quite limited.

**Comment by ghiscoding** [comment]
It might help to get the code merge if you at least test it on your side. You could just copy the updated `slick.grid.js` from the PR #495 into your local project and test it with these changes.

**Comment by 6pac** [comment]
Hmmm, had a compare and quote a lot of the logic around that seemed to disappear. Not sure why?

**Comment by ghiscoding** [comment]
@6pac that was when we did the Frozen Columns/Rows Feature, there was so much code change that I might have missed that part. There wasn't much of Examples to test with either, this example we mentioned only showed the result in the console log, so of course, I never thought of testing that when merging X-SlickGrid code.

**Comment by 6pac** [comment]
OK then, there are a few bits of code still not in the PR. I'll sit down and have a good look at it.

**Comment by ghiscoding** [comment]
yeah, that is why I made the PR as (do not merge yet) and prefer it not to be part of the next release, at least not until more tests and code check are performed.

**Comment by haqk** [comment]
@ghiscoding the fix seems to be working for my basic use case, which is similar to example 10. I haven't tested beyond that.

**Comment by ghiscoding** [comment]
closed by latest commit f12f4cc and e2ae4e059 a release will come later, in the mean time you can copy the code from master [slick.grid.js](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js) or clone it
