### ISSUE TITLE
Resizer: bottomPadding of 0 value ignored

### ISSUE THREAD

**Issue by xavier-90** [6pac/SlickGrid#504]
If setting the resizer bottom padding to 0 then the grid is rendered with a bottom padding of 20px (the default). A work-around is to set the value to '0', e.g.
```
resizer = new Slick.Plugins.Resizer({
        container: '#gridContainer',
        rightPadding: 0,
        bottomPadding: '0',
        minHeight: 150,
        minWidth: 250
      });
```

**Comment by ghiscoding** [comment]
Ahh no it's probably because it's set as `options.bottomPadding || 20`, it should be changed to 
```js
options.bottomPadding !== undefined ? options.bottomPadding : 20;
```
I didn't check at the code yet, but I think that is how I wrote it earlier.

**Comment by xavier-90** [comment]
Using '0' instead of 0 works for me.
Using SlickGrid version 2.4.22 I created a few tests as part of my investigation, one of them using the bootstrap 4 grid system layout with preheader & resizer plugin ([here if you are interested](https://github.com/xavier-90/slickgrid-demo)).

**Comment by ghiscoding** [comment]
I'm the one who created the Resizer Service and I have 3 different libs with Bootstrap (Angular-Slickgrid, Aurelia-Slickgrid, Slickgrid-Universal) that are using this service directly or a variation of it. The reason why this issue was never caught is most probably because no one ever goes with a 0 padding, I certainly don't want my grid to touch the bottom of my browser viewport, that is why I added the `bottomPadding` option in the first place. Anyway, I'll take a look and fix it later.

**Comment by xavier-90** [comment]
I tend to use Bootstrap to manage layout behaviours, padding and margins hence the discovery I guess... I have got a solution so can move forward. BTW thanks for continuing to maintain and evolve SlickGrid, great product!
