### ISSUE TITLE
Adding cell formatting at run time

### ISSUE THREAD

**Issue by aparmar** [6pac/SlickGrid#520]
I'm following the formatting example, which let's you add formatting at design time through CSS. I have a use-case where the user gets to decide their own formatting based on conditions. I can create a div or span as content of the cell and style that using a dynamically created "style" tag. However, that puts a border around it. Suggestions?

**Comment by 6pac** [comment]
You'd have to give a more specific example. The best way to do this is to start with the example and add just enough code to illustrate your issue.
If a border is default styling for the cell, then you'd need to override it with your CSS and possibly the ```!important``` attribute.

Also, you're better off asking this on StackOverflow. Issues are strictly speaking for bugs, not usage questions.

**Comment by ghiscoding** [comment]
I was going to say the same as 6pac, this should be asked on Stack Overflow...

A nice thing to know though is that Formatters are typically returning a string (90%) but another possibility is to return an object following this structure (the interface is written in TypeScript,  but it should be easy enough to understand, just note that `?.` means optional)
```ts
export interface FormatterResultObject {
  addClasses?: string;
  removeClasses?: string;
  text: string;
  toolTip?: string;
}
```
using the return as an object has the advantage of adding the css classes (with `addClasses`) to the cell container instead of the cell content. Basically if you return a string with a `<div>` then it have some extra padding all around that cell content, while if you instead return the object with `addClasses` it won't have any padding because that is the entire cell not the child content. For example, in the grid shown in the print screen below I use this approach of return an object to add a css class which has a blue background to the entire cell (to denote an editable cell). I wrote more info in this [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#formatterresultobject) for my Angular-Slickgrid lib, this might be helpful in your case (just disregard any TypeScript related stuff when using it in plain JS)

If you want to add CSS classes by following a certain logic, then it's also easy enough to use this object return by filling the `addClasses` with whatever CSS names you wish to use.

![image](https://user-images.githubusercontent.com/643976/86879404-faa73900-c0b8-11ea-841f-f73a72fbf15c.png)

I'll say it again, please ask such kind of question on Stack Overflow since this is not bug related

**Comment by aparmar** [comment]
ok...fair enough. Will create and post example problem for Stack Overflow.
