### ISSUE TITLE
Bootstrap or styles

### ISSUE THREAD

**Issue by carles9000** [6pac/SlickGrid#533]
Hi all,

Can it be used with bootstrap 4 styles?
Any 6pac slickgrid example with styles?

Thank you very much and great job.

Carlos.

**Comment by ghiscoding** [comment]
I have SlickGrid working with Bootstrap 4 in [Angular-Slickgrid](https://ghiscoding.github.io/Angular-Slickgrid) and [Aurelia-Slickgrid](https://ghiscoding.github.io/aurelia-slickgrid) libs but it's my own styles that are modified versions of the original SlickGrid styles, it's also not using jQuery UI styling. So that might not fully answer your question with SlickGrid styling itself but my libs are using this `6pac/SlickGrid` fork. I also recently created a 3rd lib [Slickgrid-Universal](https://ghiscoding.github.io/slickgrid-universal/) which also uses this fork, this new lib doesn't rely on any framework, it can be used with JavaScript/TypeScript, this lib has the same styles coming from my other 2 libs. 

So in brief, I'm not using plain SlickGrid styling anymore, my starting point a few years ago was this [reebalazs/SlickGrid-bootstrap](https://github.com/reebalazs/SlickGrid-bootstrap) and it's written in LESS, however my styling changed a lot since then and I'm now using SASS. So perhaps you can copy the styling from that repo or you can use any of my 3 libs.

Or it might just work with Bootstrap 4, have you even tried at all? I know there's a Bootstrap 3 [Example](http://6pac.github.io/SlickGrid/examples/example-bootstrap-3-header.html)

**Comment by carles9000** [comment]
Hi Mr. ghiscoding,
 
Years ago I worked with @mleibman's slickgrid and for me it was the best grid of all, this guy had things very neat in his head and very elegant code.

Now I have the need to reprogram and have seen the fork of 6pack. It has evolved and it seems perfect to me, but I have been surprised that there was no example with bootstrap 4. I will look at the bootstrap 3 example and try to change the style to bootstrap 4. I also asked to know what parts of the css I should modify but I suppose that from the example bootstrap 3 I can find out.

Thanks for your extensive answer, I will test your suggestions

Regards.
Carles

**Comment by ghiscoding** [comment]
Yes it has evolved a lot from the original fork, we added a few new controls/plugins and fixed many bugs, I think this fork will work with Bootstrap 4 but it just won't be styled as Bootstrap, it will keep jQuery UI styling because that is the default in SlickGrid unless you override it with separate CSS styling, like I did in my libs. 

I was also like you, I had to use a different grid with Angular and put SlickGrid aside but eventually came back to SlickGrid because it's just too powerful and customizable.

**Comment by carles9000** [comment]
Thanks for your time and clarifications :-)

Regards.
C.

**Comment by ghiscoding** [comment]
we now have a new Alpine Theme, see [SlickGrid 5.0 Announcement & Migration](https://github.com/6pac/SlickGrid/wiki/Major-version-5.0-%E2%80%90-ES6-ESM-and-TypeScript-Support)
