### ISSUE TITLE
Add repo to NPM?

### ISSUE THREAD

**Issue by mpetkov** [6pac/SlickGrid#55]
Is there a reason why this repo is not on npm?  It looks like the only available version is from jpsullivan but he has version 2.2.12 which is behind:
https://www.npmjs.com/package/slickgrid-6pac

It would help a lot if this fork was added to npm.

**Comment by 6pac** [comment]
i don't use npm. i have looked into it and it is not trivial to set up (possibly if you're an experienced user, it is).  
also, if i recall correctly, once it's set up for npm, you can't just reference the files in say an ASP .NET MVC project that does all its own bundling. so there would have to be two branches, npm and vanilla.
if you'd like to write a pull request, i'll see that it gets incorporated somehow.

**Comment by mpetkov** [comment]
@6pac - Actually it is just as simple as pushing the repo as-is to npm.  So no code changes are necessary.

**Comment by jpsullivan** [comment]
Hey guys, 6pac actually reached out to me and asked if it was cool if he could port a few changes over. Once this happens, I'm happy to give 6pac the npm name (if possible) or add a deprecation message to my npm install script. 

Does anyone have thoughts about the best way to move forward with that?

**Comment by mpetkov** [comment]
You would have to keep the existing one for sure because you don't want to break other people's projects that depend on it.  So if the npm repo will continue to be updated via the @jpsullivan fork, then business as usual.  However, if it is decided that the @6pac fork will be the main one and all updates will go here, then you will have to create a new npm repo to avoid confusion.

That's just my 2 cents based on my npm experience :smile:

**Comment by jpsullivan** [comment]
Yeah, that was sorta what I was thinking too. I can update mine though to provide a deprecation warning when updating or doing a fresh npm install though to point users in the right direction. 

Personally, I'd rather use the "official" fork versus my own, and I assume many users would prefer the same.

**Comment by 6pac** [comment]
I tend to agree on a single point, not that i want or need control over it, but with two repo owners it's definitely easier for things to get stale on one or both sides.
The thing that worries me is there are people doing SlickGrid updates to lose the jquery dependencies (haven't got around to testing it yet, but this would be another repo), and other agitating for the frozen columns feature (and again). So with npm and non-npm versions of each, things stand a chance of getting quite out of hand regarding the number of repos. Ironically, I think npm was built to manage this very situation.

Perhaps the best idea is to just duplicate the necessary .js files with an -npm suffix (eg. slickgrid-npm.js). I have seen that done elsewhere. The npm config could be pointed at those files.

**Comment by 6pac** [comment]
OK, we are proudly now on NPM. Thanks to Roman Shtylman for giving me the keys to the 'slickgrid' npm name (i thought it should be used in preference to 'slickgrid-6pac'). Many thanks to @jpsullivan for providing the bulk of the solution.

I have taken the approach of creating a separate file ```slick.grid-npm.js```, and similar for dataview and core, so we have a version that works with npm and one without.
It's now up to me to keep them in sync, and to this end I have added a ```scripts``` folder containing a bash script that will delete the ```-npm``` files, copy them from the main files and then apply a patch containing the npm-enabling code (this can be run from the MinGW bash Git CLI in Windows).

I don't use npm and I am rather suspicious that there aren't enough ```require```s in there to fully support slickgrid. If it turns out to be the case that most files need to be modified, then I'd either start another repo, split a branch or maybe just move the npm copy of the grid to its own folder and use an automated build system similar to what I have set up already.

Let me know how it goes. Bower and NuGet support coming soon.

**Comment by 6pac** [comment]
Released version 2.3.3

**Comment by 6pac** [comment]
Sorry for the flip-flopping (I figure it's better to change early rather than wait), but I have decided to restructure the way the npm files are stored. They are now in a separate ```npm``` folder.

From what I can see, npm has two uses. Firstly, it delivers packages of files, like Nuget or Bower. This is non-controversial. But secondly, it allows dependencies to be expressed using code within the js files, and then allows compilation of single deployment files from a bunch of components (using the dependencies to figure out what to include). Because SlickGrid is inherently a toolkit, rather than a finished product, this means that at some stage probably every js in the bundle file will have to be tweaked to add the npm dependencies and allow an automated build. Hence the separate folder.

And that's also why I'm not going to attempt to deliver a minified (or otherwise) standard 'deployment' file for SlickGrid in Nuget or Bower - there are just too many plugins and controls that developers may want to include or leave out.
Slickgrid, for now at least (or until someone mounts a convincing argument on how to do it otherwise), will remain a source-only toolkit that requires being hand-built, or being built by your own tools, for deployment.

All this said, I don't actually use any of these deployment tools, since I use ASP .NET MVC, which delivers for browser only, and has a built in bundling and minification tool. So I'm waiting to be guided (best by pull request :-) by those who are expert in their use.

**Comment by 6pac** [comment]
Release 2.3.4
