### ISSUE TITLE
Remove old jquery references from lib folder

### ISSUE THREAD

**Issue by bogdanrech** [6pac/SlickGrid#565]
We are working on a project which go through a series of security/vulnerabilities tests. 
Are all jquery versions in lib folder used by slickgrid? 
jquery-1.8.3.js
jquery-1.11.2.js
jquery-1.11.2.min.js
jquery-1.12.4.min.js
jquery-2.2.4.js
jquery-3.1.0.js
If not please remove unused versions.

**Comment by ghiscoding** [comment]
The answer is "No" they're not all required... but it might be risky to remove all unused libs because there might be some users who still reference them in their code and if we remove them then we might break their code. But if you don't use them then just don't reference them in your code, it won't be part of your build and shouldn't be showing up in your build and so shouldn't be caught in your vulnerabilities test. 

> If not please remove unused versions.

The way you ask is a just a bit rude... just saying
This is an Open Source project

**Comment by 6pac** [comment]
I have the three jQuery versions because I needed to run separate tests for earlier versions of the 2.x tree, late versions of the 2.x tree, and the 3.x tree. These are perhaps less relevant now than they were 5 years ago, but they are there for a purpose.

Slickgrid is basically a toolkit - it's expected that you'll need to put together your own build. We don't want to customise it for particular environments. @ghiscoding has several repos that provide more targeted versions of the project, but I'm not aware of a 'production' finalised package that is drop-in.

**Comment by bogdanrech** [comment]
Hi,
Thank you for your answer and clarification. I'll try removing each lib and test the results.
