### ISSUE TITLE
Is there any plan to have Blazored version of slickgrid?

### ISSUE THREAD

**Issue by diskman** [6pac/SlickGrid#609]
I am looking now for some alternative for slickgrid in blazor project. It is very hard to choose something  similar to have features available in slickgrid.

**Comment by ghiscoding** [comment]
most probably not but you can take a look at my lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal), it's written in TypeScript and is a wrapper on top of this fork. Since it uses TypeScript, there's CommonJS/ESM builds that might be more suitable for Blazor!?! But I'm not sure since I've never used Blazor, I just heard of it

**Comment by 6pac** [comment]
Looks like Blazor/wasm can run alongside js in the browser. Slickgrid is always going to be js/typescript, so will never be native Blazor, but you should be able to interoperate it alongside your Blazor code. I'm going to close this issue now.
