### ISSUE TITLE
Multi-Select filter bug - not working on values that contain a space.

### ISSUE THREAD

**Issue by shaneyEB** [6pac/SlickGrid#611]
Currently, I am using operator: OperatorType.inContains, and the filter only works if the values do not contain any spaces in them.  It will not return any results for values that contain a spaces.  Please see the ShareX for more details.

https://user-images.githubusercontent.com/85243194/120511421-690f7c80-c398-11eb-8417-122d184dd8f9.mp4

**Comment by ghiscoding** [comment]
Hello, I'm not really sure why you've opened this issue in SlickGrid core lib because this is an Angular-Slickgrid specific feature. 
The `IN_CONTAINS` filter uses the code from this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/filter-conditions/filterUtilities.ts#L76) which is 
```ts
    case 'IN_CONTAINS':
      if (value2 && Array.isArray(value2) && typeof value1 === 'string') {
        return value2.some(item => value1.split(/[\s,]+/).includes(item));
      }
      return false;
```
So I don't know what your text values are but it probably doesn't pass this test condition. 
What's the reason that you're using the `inContains`? 
You might want to try `inCollection` that I added few months ago in this [PR](https://github.com/ghiscoding/Angular-Slickgrid/pull/722)

**Comment by shaneyEB** [comment]
Thanks so much for your help.  The IN_COLLECTION is working for my multiselect.  I had to re install to get your latest fix that was put in on March 18.  I also want to apologize for putting this request in the wrong place.  I will submit future request in the angular-slickgrid support.  I do want to point one thing out on example 27 it did not work for me.  If you select a value with a space it does not work.  Please see picture below.   Again thank you so very much for your help.  Have a wonderful day!
![example27](https://user-images.githubusercontent.com/85243194/120526826-a596a480-c3a7-11eb-88ea-93385d771a85.png)

**Comment by shaneyEB** [comment]
Thank you for your speedy response and your great support.  Have a blessed day!

**Comment by ghiscoding** [comment]
>  I also want to apologize for putting this request in the wrong place. I will submit future request in the angular-slickgrid support.

No problem, just wanted to highlight this because we are 2 different projects and maintainers of this lib 😃 
Sometime the issue(s) are in Angular-Slickgrid but sometime they are in SlickGrid core lib, it all depends what the issue is, if you know which one is which then that helps us ;)

> If you select a value with a space it does not work.

Ok good to know, I think the regex is too restrictive, I'll take a look at it later, thanks for the info

Glad to know you got it working
Cheers ⭐

**Comment by ghiscoding** [comment]
and before I forget, I took a quick look at it and fixed it, I simply needed to add a `trim` to the string values to inspect and now it works. So thanks for reporting this (even if it was in the wrong lib) 😉 

```ts
  case 'IN_CONTAINS':
      if (value2 && Array.isArray(value2) && typeof value1 === 'string') {
        return value2.some(item => value1.split(/[,]+/).map(val => (val.trim())).includes(item));
      }
      return false;
```

![image](https://user-images.githubusercontent.com/643976/120535466-ffe83300-c3b0-11eb-9539-f19cf6e6e031.png)
