### ISSUE TITLE
Is there an example of cell merging?

### ISSUE THREAD

**Issue by Jiangsongheng** [6pac/SlickGrid#614]
I want cells with the same content to merge into a large, cross row cell. It's like merging cells in Excel.

![1](https://user-images.githubusercontent.com/59638621/121137718-88f7e200-c869-11eb-9510-6c949d83e116.png)

**Comment by 6pac** [comment]
I don't think this has ever been done. There was an experimental branch that played around with variable length rows, but it wasn't compatible with a lot of the other features.  
It might be easiest to do by using a formatter and just trying to not display the bottom border on those cells.

relevant examples:  
- http://6pac.github.io/SlickGrid/examples/example-colspan.html
- http://6pac.github.io/SlickGrid/examples/example2-formatters-event.html

You're probably better off asking on StackOverflow in future

**Comment by Jiangsongheng** [comment]
ok, thanks.

**Comment by ghiscoding** [comment]
That was possible in another fork [GerHobbelt/SlickGrid](https://github.com/GerHobbelt/SlickGrid) fork. I'm not sure if it's feasible with our fork since we now have the frozen feature, which I don't think GerHobbelt has, so it might or might not be doable, but it would be nice to have the following. I did not look at the code at all, I just clone his repo and looked at all the samples he has (a lot of them). That would be really great if you can make it working and contribute with a new Example. 

Thanks

- [example-0031-row-span.html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0031-row-span.html)
- [example-0032-row-span-many-columns.html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0032-row-span-many-columns.html)
![image](https://user-images.githubusercontent.com/643976/88747240-60b53800-d11c-11ea-8727-a15abadbab74.png)

**Comment by ghiscoding** [comment]
🔈 Rowspan is now officially supported via the new [v5.15.0](https://github.com/6pac/SlickGrid/releases/tag/5.15.0) release
