### ISSUE TITLE
Make a Nuget package available?

### ISSUE THREAD

**Issue by adamatyork** [6pac/SlickGrid#62]
Similar to #22 , it would be great to have a nuget package available to make it easier to update from original SlickGrid to this Fork in commercial dev environments.

**Comment by ghiscoding** [comment]
Closing since we provide an [NPM](https://www.npmjs.com/package/slickgrid), NuGet becomes unnecessary with ASP.Net Core

**Comment by 6pac** [comment]
Actually, we DO have a Nuget package already.
And with .NET Core isn't Nuget front and center?

**Comment by ghiscoding** [comment]
@6pac 
On our side, we use .Net Core at our work and the story is that basically NuGet is all good for the backend stuff but all our frontend (Angular, jQuery, SlickGrid), it's all NPM only. The thing is, .Net Core doesn't care anymore which package manager you use and that's a good thing since you, as a lib owner, can focus only on 1 package manager. So all in all, we use NuGet only for backend packages and NPM for all frontend and that's it. If you wish to support 2 package manager, that's up to you, but I don't think it's necessary anymore in this new world. You can still reopen if you wish to bring support to NuGet
