### ISSUE TITLE
Filter doesn't work correct with tree

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [6pac/SlickGrid#620]
The top filter "And title including" doesn't work correct with the grid with a tree.
SlickGrid-2.4.38
E.g.:
/examples/example5-collapsing.html
![изображение](https://user-images.githubusercontent.com/67962205/123602023-024b7a80-d801-11eb-87c9-33f9dc8e932d.png)
![изображение](https://user-images.githubusercontent.com/67962205/123602058-0a0b1f00-d801-11eb-8272-06f7860b731a.png)

**Comment by 6pac** [comment]
I remember this one. The reason is that the parent nodes of 11 are being filtered out, so it no longer has a place in the list. There are two possible behaviours: (1) keep the filtered nodes parent nodes (even if they don't match the filter), and (2) apply the filter, then re-apply the tree (resulting in nodes at depth possibly becoming top level nodes.  
Which one are you after?

**Comment by SergeyBeloglazovRL** [comment]
Thank you for the answer!
Yes, I have made additional experiments and have came to the conclusion, you have wrote. If a parent have to be hidden, children are hidden too.
I don't think, that reassembling tree (the 2nd way) is intuitive for user. 
I think the grid should show parent lines, even they don't match the filter, if any child does.
I think it should be like file/directory searching when you get in results full paths with upper subdirectories.

**Comment by ghiscoding** [comment]
The Example that was created originally was only there demo the indentation and it wasn't caring about sorting/filtering as a Hierarchical Tree grid would do. I had worked on this, with the help of another user, in my own repo but never managed to merge the feature here. My code has it all, it has correct Filtering (if you search for something that is in the child, then the parent will remain, that is the correct way to use Tree Data) and the Sorting also work.. all of that is possible via a few recursive functions (because Tree Data is all recursion). You can take a look at the Example [example-tree-data.html](https://github.com/ghiscoding/SlickGrid/blob/master/examples/example-tree-data.html), it requires a new plugin we created specifically for Tree Data [slick.treedata.js](https://github.com/ghiscoding/SlickGrid/blob/master/plugins/slick.treedata.js)

here's an animated gif of it
![glsGjAsDUp](https://user-images.githubusercontent.com/39010050/82159178-c7041b80-988c-11ea-836d-422f288f5f44.gif)

That code was then used in 3 other libs written in TypeScript, I use `6pac/SlickGrid` fork for the main code but the Tree Data is outside of this (I have few services in my libs, like FilterService, SortService, ...)... anyway all that to say, here's 2 live demos in my libs using the technique written in previous paragraph. Slickgrid-Universal [Example 5](https://ghiscoding.github.io/slickgrid-universal/#/example05) and [Example 6](https://ghiscoding.github.io/slickgrid-universal/#/example05), my other 2 libs also have the same Examples (Angular-Slickgrid and Aurelia-Slickgrid)

It's a long reply but basically, if you want to implement that in pure SlickGrid JS, take a look at the Example I provided links in my first paragraph. I should merge it back here eventually, just never took the time because the aggregation part was never really finished

**Comment by SergeyBeloglazovRL** [comment]
Thank you, @ghiscoding! I will try using your solution.

**Comment by SergeyBeloglazovRL** [comment]
@ghiscoding 
Now I'm using your version. Got some issues, made some workarounds. Wrote in repo.
By the way, I find more convenient example for tree filtering.
It's angular UI Grid. 
http://ui-grid.info/docs/#!/tutorial/Tutorial:%20215%20Tree%20View
It isn't seemed like a complete thing. So I continue using https://github.com/ghiscoding/SlickGrid/
Angular UI Grid filters tree data hiding children, that don't match the filter:
![изображение](https://user-images.githubusercontent.com/67962205/124565671-f7b96280-de4a-11eb-8151-5184ad5f4ec7.png)
![изображение](https://user-images.githubusercontent.com/67962205/124565710-00119d80-de4b-11eb-8acf-70df8107c818.png)
It contrasts with ghiscoding's SlickGrid behaviour:
![изображение](https://user-images.githubusercontent.com/67962205/124565902-3222ff80-de4b-11eb-8056-7263a21aeef4.png)
![изображение](https://user-images.githubusercontent.com/67962205/124565920-38b17700-de4b-11eb-9e8f-486814080341.png)


Filtering the root:
![изображение](https://user-images.githubusercontent.com/67962205/124566453-b8d7dc80-de4b-11eb-99b5-49d7dc3033b5.png)
![изображение](https://user-images.githubusercontent.com/67962205/124566475-be352700-de4b-11eb-88cf-fcf80c89204f.png)

**Comment by ghiscoding** [comment]
@SergeyBeloglazovRL I will create a PR soon to merge this into this repo and you can push some fixes if you want in the future. in your case I think you want to click that button to exclude child from the showing up

![image](https://user-images.githubusercontent.com/643976/124605313-c71cfd00-de39-11eb-8090-c0f72121bebb.png)

I don't use that code directly in my libs, I just took some pieces of that code (for example showing all child of the tree when filtering is an option I don't have in my libs). I had lots of help from another great person to build that and he did that piece of include/exclude child in the tree when filtering and since that part is not in my lib, I don't remember how it works but I remember it came from a demo found on Ag-Grid which was an extra config to optionally use

**Comment by SergeyBeloglazovRL** [comment]
Unfortunately, I can't see any difference whether it is set on or off:
![изображение](https://user-images.githubusercontent.com/67962205/124621116-af1d9b80-de82-11eb-810c-b1cfafc9c250.png)
![изображение](https://user-images.githubusercontent.com/67962205/124621142-b3e24f80-de82-11eb-896a-291504c77744.png)

**Comment by ghiscoding** [comment]
again sorry but I'm not sure what that code does, I'm however pretty sure it would be that flag, you can look at the code itself. I can't help you more than that, it is not the code I use in my own libs (it's only a portion of it). So you'll have to troubleshoot yourself

**Comment by SergeyBeloglazovRL** [comment]
Ok, thank you for helping!

**Comment by ghiscoding** [comment]
@SergeyBeloglazovRL 
So I tried troubleshooting the code and I was right on the flag, and if we do use it and modify this piece of code from `slick.treedata.js` with the following (adding an `if` wrapper as shown below)

```diff
function innerAddAll(child, collapsedFlag) {
  //now works with nested array of objects or object of objects:
  const iterable = (child instanceof Array) ?
    child :
    Object.values(child) || [];
  for (let id of iterable) {
    const childCopy = { ...id };
    delete childCopy[childrenPropName];
    childCopy.__collapsed = collapsedFlag;
    //filteredChildrenAndParents.push(childCopy);
    delete childCopy[childrenPropName];
+   if (!gridOptions.excludeChildrenWhenTreeDataFiltering) {
      filteredFlatObj[id[identifierPropName]] = {...childCopy, ...aggregatorPropsInitObj};
+   }
    tempFlatObj[id[identifierPropName]] = {...childCopy};
    id[childrenPropName] && innerAddAll(id[childrenPropName], collapsedFlag);
  }
}
```
 then the demo works as expected. I'm not sure it breaks anything but hey at least it starts to work so give it a try. I'll push a PR soon including that change.

**Comment by SergeyBeloglazovRL** [comment]
Thank you!

**Comment by 6pac** [comment]
Happy to merge this to the base Slickgrid if that's straightforward to do.

**Comment by ghiscoding** [comment]
This is overly complex and it will not be addressed in this project, the example were merely for demo purposes and we know that filters are not working as expected. 

However if you still need this feature, I do have a full Tree Data feature in my other project [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which is using SlickGrid, you can see these 2 demos [Example 5 - parent/child](https://ghiscoding.github.io/slickgrid-universal/#/example05) and [Example 6 - hierarchical](https://ghiscoding.github.io/slickgrid-universal/#/example06), it works correctly with Filter, Sorting and I even added Tree Data Aggregator (totals)

If anyone want to fix the Tree Data filters in here, please go ahead with a Pull Request, but it will not be fixed by us maintainer and so I will close this issue because I also provided an alternative
