### ISSUE TITLE
Horizontal/vertical scroll bars flipflopping upon every update/redraw

### ISSUE THREAD

**Issue by zakimaksyutov** [6pac/SlickGrid#70]
My app uses options.forceFitColumns = true (my understanding of this setting = no horizontal scrollbar). But in some cases, when canvas still fits into viewport, I see either 1) both scrollbars present or 2) horizontal and vertical scroll bars flip flop every redraw [horizontal scrollbar is visible, vertical is hidden; then vice versa; ...]

I tried to debug the math SlickGrid is doing but my current perception is it is not the one which is causing it (maybe html layout causes it?).

The solution which solved this problem for my app is to set "overflow-x" to "hidden":

```
      $viewport = $("<div class='slick-viewport' style='width:100%;overflow:auto;outline:0;position:relative;;'>").appendTo($container);
      $viewport.css("overflow-y", options.autoHeight ? "hidden" : "auto");
      **$viewport.css("overflow-x", options.forceFitColumns ? "hidden" : "auto");**

```

I'm not sure whether something additional needs to be done for cases where users can change forceFitColumns option (it's not exposed in my app).

Thoughts?

**Comment by mcgilman** [comment]
I believe I'm seeing the same behavior with a sporadic horizontal scrollbar. It may be being caused by a recent change in jquery [1]. It seems the available width/height now contains more precision which is causing an additional iteration when calculating column widths.

[1] https://jquery.com/upgrade-guide/3.0/#breaking-change-width-height-css-quot-width-quot-and-css-quot-height-quot-can-return-non-integer-values

**Comment by 6pac** [comment]
I will have a look. I suppose the easy solution is just to round/truncate the returned value. If possible, a reliable test case to display the bug would be welcome. Is it possible to mod one of the examples?

**Comment by 6pac** [comment]
Incorporated ```$viewport.css("overflow-x", options.forceFitColumns ? "hidden" : "auto")```
