### ISSUE TITLE
This is happing on my grid.  This is what is driving me nuts:

### ISSUE THREAD

**Issue by RicardoSemDedao** [6pac/SlickGrid#732]
This is what is driving me nuts:
              There are no errors in the code, it works well on different computers and even in different browsers. But this particular problem is happing on my local host in chrome: 
              Can anybody give me an idea of what might be wrong here? 
MS: Edge
![image](https://user-images.githubusercontent.com/126813965/222562491-a8797459-bb4e-4094-9d8d-485d0ff661af.png)

and This is Chrome
![image](https://user-images.githubusercontent.com/126813965/222562718-44ddd1d8-73b1-4cb5-9679-e6c328783706.png)

_Originally posted by @RicardoSemDedao in https://github.com/6pac/SlickGrid/issues/731#issuecomment-1452588938_

**Comment by 6pac** [comment]
@RicardoSemDedao If you want help, you need to provide us with a self contained file that we can run from the examples folder of the repo, that shows the problem.  You can attach the file by dragging it onto your reply.

Also, you should be posting this on StackOverflow rather than here, since this is an implementation problem, not a bug in the repo. However if you can provide the self contained file here, I will troubleshoot it,
