### ISSUE TITLE
Dragging a column does not automatically move the scrollbar.

### ISSUE THREAD

**Issue by NemoDima** [6pac/SlickGrid#735]
In the new version (3.0.4) for some reason, dragging a column does not automatically move the scrollbar.
https://jsfiddle.net/vovaltus/as9oLx3z/13/

In the old version (2.4.45) this worked without any problems.
https://jsfiddle.net/vovaltus/uagw8Lqc/73/

Perhaps we are missing something in the new version?

**Comment by ghiscoding** [comment]
it might be something that jquery drag was adding, you can try to import it [jquery.event.drag-2.3.0](https://github.com/6pac/SlickGrid/blob/master/lib/jquery.event.drag-2.3.0.js), when it's loaded it will take precedence over the new [slick.interactions.js](https://github.com/6pac/SlickGrid/blob/master/slick.interactions.js), see if that helps.

**Comment by ghiscoding** [comment]
This seems to be caused by the switch to SortableJS and they have a plugin SortableJS [AutoScroll](https://github.com/SortableJS/Sortable/tree/master/plugins/AutoScroll) that you can maybe try, I was not able to test myself but that seems to be the only way to fix this issue since SortableJS seems to block drag outside of its container.
