### ISSUE TITLE
jQuery change means you can no longer set space separated list of class names

### ISSUE THREAD

**Issue by tomqwpl** [6pac/SlickGrid#795]
Prior to the jQuery removal code in e.g. headerbutton.js was like this:
```
btn.addClass(button.cssClass);
```
I believe that "addClass" is a jQuery method. It accepts a space separated list of class names.
Now the code is like this:
```
btn.classList.add(button.cssClass);
```
This accepts only one class name. If you give is a space separated list of class names DOMTokenList complains. If you attempt to pass in an array of class names, you get a comma separated list of classnames out, and that's not valid syntax for the class attribute. DOMTokenList.add does allow a varargs list to be passed, but you would have to call it as
````
btn.classList.add(...button.cssClass);
````
But that would presumably only work if cssClass was an array.

Why do I want a list of classnames? Rather than using an image, I'm wanting to use an icon from an icon library like codicons, and that's done by specifying a list of class names, rather than an image file.

**Comment by ghiscoding** [comment]
Note that `cssClass` is singular which typically mean only 1 class, however I do understand that because it comes from jQuery then it wasn't obvious that we could add multiple. Anyway, I thought I had fix them all but after taking a quick look, it looks like I forgot to change most of them, here's 1 fix I applied to the Grid Menu (spread operator `...` plus the split does the job)

https://github.com/6pac/SlickGrid/blob/b458c235cfa1b3b7b2b2782469eeed5aa37099d8/controls/slick.gridmenu.js#L216-L218

this fix should be applied to all Controls and Plugins, a PR would be welcome before @6pac creates another release

**Comment by tomqwpl** [comment]
I know for a fact that the microsoft's vscode jupter extension does this, for example:
```
c.header = {
                        buttons: [
                            {
                                cssClass: 'codicon codicon-filter codicon-button header-cell-button',
```
So if they ever upgraded they would hit this.

If I submitted a PR, all I would do is do a search for "classList.add" and look for examples that aren't string literals, and aren't class names that have obviously just been constructed, things that plausibly look like they come from options passed in. There don't seem to be that many instances. I would have no way to test any changes beyond that.

**Comment by ghiscoding** [comment]
I already provided you the fix, you can simply do a search across the project for the word "cssClass" and update them all with the code I provided. I already tested out a while back and I know it works, I just forgot to apply it to all instance of "cssClass" and at the time I had just fixed the one that I encountered but like I said we should fix them all

**Comment by tomqwpl** [comment]
Cool. If you're happy that that's an OK way to proceed, then I will try and create a fork and submit a PR. I will try and do that tomorrow.
