### ISSUE TITLE
Add a simple 1-page ESM example

### ISSUE THREAD

**Issue by JerryI** [6pac/SlickGrid#864]
Hey there. This is an amazing tool,but frankly speaking, I am feeling lost 

I tried a couple of examples bundling them on CodeSandbox, but did not manage to make them work properly
![Screenshot from 2023-10-15 18-12-40](https://github.com/6pac/SlickGrid/assets/4111822/c7764ebe-d550-4f7e-bbf4-487758523c01)
or like this
![Screenshot from 2023-10-15 18-13-13](https://github.com/6pac/SlickGrid/assets/4111822/a9ec7855-397a-4d4b-bb53-9cdabc8c6ec6)

There are so-many .css files to be included, could it be bundled to a single CSS? I also noticed that some of them are scoped to `#myGrid` id, which is not a good thing, when someone tries to embed it into another project.

Typescript examples are helpful, it i believe people would appreciate to the simplest stupid 1 file-page example, that can run perfectly after copy & paste to a codesandbox or repit.

**Comment by 6pac** [comment]
Hi @JerryI, I'll leave it to @ghiscoding to respond about packaging, because he has just completely reworked all that. But I just wanted to say that I have had issues with Slickgrid and various sandboxing sites in the past. Some of them just don't seem to be able to cope with all the references. You should be able to use the examples on GitHub though, and if you download the repo, the examples should work in-place when opened in a browser.

**Comment by ghiscoding** [comment]
You should use the new Alpine Theme, there's more info in the [Release 5.0](https://github.com/6pac/SlickGrid/wiki/Major-version-5.0-%E2%80%90-ES6-ESM-and-TypeScript-Support) announcement. The new Alpine Theme is a good starting point but will never include CSS for all Controls/Plugins and that is intended. There are new ESM demos on top of the [Examples](https://github.com/6pac/SlickGrid/wiki/Examples). 

> There are so-many .css files to be included, could it be bundled to a single CSS? I also noticed that some of them are scoped to `#myGrid` id, which is not a good thing, when someone tries to embed it into another project.

That was maybe the case with the old classic theme but shouldn't be the case with the new Alpine Theme... actually I just took another look and yes it does have a `#myGrid` but it's mainly for compatibility reasons, we emphasizes users to use the `.slickgrid-container` CSS class name instead, this is better than `#myGrid` but they both work.

Also note that SlickGrid was created from the start to be like an IKEA product, you install and include only the pieces that you're interested in and by default it's very basic (no Controls/Plugins included, they are separate and optional) and again that is intended, we will not change this because **no one** will ever use all Controls/Plugins. If you don't like this approach and prefer to have an all-in-one lib, then I suggest you take a look at my other lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which serve different approach and use case, it only 1 CSS/SASS file for that lib. The 2 projects are both derived from the same core but they serve different use case. 

If you still think that is not ideal, then you can always contribute to the project. Just a reminder that this is an Open Source project and we are not paid at all to support the project, it is all done in our spare time. Contributions are welcome if you think you can improve the project. With that said, I think we can close this issue

**Comment by JerryI** [comment]
Thank you a lot for your replies, now it does look clear for me
