### ISSUE TITLE
onScrollEvent - Add Row and Cell

### ISSUE THREAD

**Issue by pbower** [6pac/SlickGrid#961]
### Clear and concise description of the problem

Hi there,

Through server-side data retrieval work I've found it useful having the Row and Cell available within the onScrollEvent in Slickgrid.

I noticed recently @ghiscoding that you added row and column to the gridEvents interface src/models/gridEvents.interface.ts , possibly in advance of altering this event or in relation to new features in your downstream products.

Therefore, I'd like to share the implementation I've used to fulfil the interface within the library, and propose that 'Row' and 'Cell' be added to the onScrollEvent, complementing the pixel position that fire in the current setup.

Note - I had a go at 'patch-package' before sharing back, as I'm happy to lodge a pull request, but not 100% across the current relationships between the JS and Typescript files, plus testing setup etc. , so I thought I'd reach out here first. 

If you'd like me to have a go at something I'd be happy to.

### Suggested solution

The below image represents methods from slick.grid.ts:

1. **getViewportCell() :**
New method for returning the cell at a given scroll position.

2. **getRowFromPosition** and **getCellFromPoint** :
These are existing methods in slick.grid.ts.

<img width="1349" alt="image" src="https://github.com/6pac/SlickGrid/assets/37089506/c64da60e-eb7b-4fa4-b960-f7f3f0584271">

**Propose:**

1. **Add Method to obtain the top-left Viewport cell** to slick.grid.ts. Or, any equivalent solution.
2. **Add row and cell to the onScrollEvent**, so that it is accessible via args. I thought I found this in the library, but when I made a local alteration it didn't reflect in the event, I instead handled this in my app's eventHandler, like so:
<img width="531" alt="image" src="https://github.com/6pac/SlickGrid/assets/37089506/6f85d08e-ce79-4766-9ec1-03128cd77cf4">

which returns the position ok:
<img width="526" alt="image" src="https://github.com/6pac/SlickGrid/assets/37089506/6ccd5932-784d-4461-8270-5bed6cf121dd">

3. **Possible bug-fix** :
In my tests I did notice that the existing (cell - 1) offset for the columns in getCellFromPoint's return statement moved it back too far, starting at '-1' rather than 0 from a neutral scroll position, so I'm wondering whether getCellFromPoint is meant to return { row, cell} rather than { row, cell-1 }? Noting this is minor, and I do have the column title row pinned and visible in case that affects things.

Note: This has not been tested with grouped rows and/or other library features, in case this impacts things.

### Alternative

This could be implemented in a number of ways. This proposal leverages the inbuilt methods within slick.grid.ts
If there is another desired pathway or existing work here no stress at all.

### Additional context

Enables apps to respond to the users' scrolled position within the dataset. Benefit examples may include:
- easier row-based retrieval mechanisms based on the users' current scroll position within the dataset.
- other opportunities, such as a program responding to when a user is at a 'large' scroll position with different data management features.

Thanks for considering this.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
@pbower so I propose you create a PR for the -1 bug, but for the rest I think it would be best if we keep it the same. I'm still open for discussion in case I missed something

**Comment by ghiscoding** [comment]
I searched in the original SlickGrid and it looks like the -1 was there from the start, so I didn't see any bug fixes on this particular line or anything at all.

Actually it's possibly related to this other bug fix https://github.com/mleibman/SlickGrid/issues/1093 which probably added back the -1 offset

**Comment by ghiscoding** [comment]
@6pac do you have any clue why there's a -1 on `return { row, cell: (cell - 1) };` to calculate `getCellFromPoint()`?

https://github.com/6pac/SlickGrid/blob/f8574ba629eaadc1a2187d7325fe487bd37162ba/src/slick.grid.ts#L5583-L5600

**Comment by 6pac** [comment]
It makes sense. The algorithm is to keep adding column widths until the cumulative column width is greater than the input position. So the input position is within the column before the one that terminates the loop.

**Comment by ghiscoding** [comment]
@6pac but @pbower mentioned this 

> In my tests I did notice that the existing (cell - 1) offset for the columns in `getCellFromPoint`'s return statement moved it back too far, starting at '-1' rather than 0 from a neutral scroll position, so I'm wondering whether `getCellFromPoint` is meant to return { row, cell} rather than { row, cell-1 }? Noting this is minor, and I do have the column title row pinned and visible in case that affects things.

So is it really supposed to be with an offset of -1?

**Comment by 6pac** [comment]
The logic is correct, but I think this is a fencepost error. Try making it 

    for (let i = 0; i < this.columns.length && w <= x; i++) { 

and see if that fixes the problem with the tests. It fixes ```getCellFromPoint(0,0)```

**Comment by ghiscoding** [comment]
> The logic is correct, but I think this is a fencepost error. Try making it

Yeah so you seem to be suggesting the same change that was mentioned in here https://github.com/mleibman/SlickGrid/issues/1093

![image](https://github.com/6pac/SlickGrid/assets/643976/8034d213-2c8f-4307-a13f-aa24a30c5341)


The funny thing is that you mentioned that you have applied it in here, but I couldn't find the change even when going back to 2.x early days. However, I know that a lot got overwritten when we merged X-SlickGrid in here, that was a very large PR at the time....

@pbower could you please try the suggested code change shown above and see if that fixes your bug. You are the best person to confirm this since you are having the issue and I never used this method myself. So please provide feedback

**Comment by 6pac** [comment]
Yes, it looks the same, though I didn't look at the previous PR. They also removed the check for negative column index.
It does appear that despite the comment, it never got updated in the new repo.

**Comment by pbower** [comment]
> > The logic is correct, but I think this is a fencepost error. Try making it
> 
> Yeah so you seem to be suggesting the same change that was mentioned in here [mleibman/SlickGrid#1093](https://github.com/mleibman/SlickGrid/issues/1093)
> 
> ![image](https://private-user-images.githubusercontent.com/643976/294711165-8034d213-2c8f-4307-a13f-aa24a30c5341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDY2OTksIm5iZiI6MTcwNDgwNjM5OSwicGF0aCI6Ii82NDM5NzYvMjk0NzExMTY1LTgwMzRkMjEzLTJjOGYtNDMwNy1hMTNmLWFhMjRhMzBjNTM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMzE5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDA1ZThhZjBlYmE3MGY2M2I4M2IzNTlhMGE1OWY3ZThiYmM1ODkyOGNjYjZhNTg0Y2U0NTRhMzY5YTg0MTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MmbFcVYm30nvm1_qy_2pU_ziAsqn19vTbD4nhdu4zl8)
> 
> The funny thing is that you mentioned that you have applied it in here, but I couldn't find the change even when going back to 2.x early days. However, I know that a lot got overwritten when we merged X-SlickGrid in here, that was a very large PR at the time....
> 
> @pbower could you please try the suggested code change shown above and see if that fixes your bug. You are the best person to confirm this since you are having the issue and I never used this method myself. So please provide feedback

Hi @ghiscoding 

Yes, sure thing. I've just got back from holidays, so will jump onto it at some point this week.

Happy new year both.

Regards,
Peter

**Comment by 6pac** [comment]
Forgive me if this does not make sense - I'm not really familiar with this function and I'm guessing to some extent.

I'm assuming that (x,y) is the position in the viewport (we should probably add comments confirming this).  ```getRowFromPosition()```  adds the offset to get the position in  the absolute virtual pane, accounting for vertical scrolling.

The cells are the displayed column elements.

The logic for columns is simple enough - just add non-hidden column widths until we are past the requested width, then back up a column.  However it does not appear to be allowing for H scrolling - ie. x is assumed to be the position on the absolute pane, not the viewport.
Assuming we want to return the column index for a x position in the viewport, we really should be adding an offset for the start of the viewport.

So how about: 

          for (var i = 0; i < columns.length && w <= x + scrollLeft; i++) {

(should change this so it doesn't do the ```x + scrollLeft``` calc each iteration, if it works!) 

Does anyone have some code that uses this function?

**Comment by ghiscoding** [comment]
> @ghiscoding those are some crazy test results. Should we be even allowing negative (x,y)? I don't think it should be able to return a negative row or cell at all.

well that is why I was asking you, I thought you knew because I was surprised as you are haha 😉 but even then I'm not sure we should return 0,0 when outside the viewport, I guess it would be ok to return -1,-1 just to remove possible confusion that the coordinate is really outside of the viewport

I'm not sure what you mean about the previous paragraph though, the correct description of the method `getCellFromPoint()` is the following. I changed it a bit to be more explicit but anyway the 2n sentence is the same as what the original author wrote I believe. So in my tests, the `DEFAULT_COLUMN_WIDTH` is equal to 80px and the `DEFAULT_COLUMN_HEIGHT` is 25px which are the default values in SlickGrid, so if we provide coordinate of 5,5 it should really return `{ row: 0, cell: 0 }` and we provide 85,30 then it should return `{ row: 1, cell: 1 }` but it doesn't at the moment, I think we need to adjust the logic to do this and possibly `{ row: -1, cell: -1 }` when it's outside the viewport (unless you prefer 0,0 but I think it shouldn't)

> Returns row and cell indexes by providing x,y coordinates.
Coordinates are relative to the top left corner of the grid beginning with the first row (not including the column headers).

**Comment by 6pac** [comment]
I think there's something wrong with your tests.
(1) I think negative inputs should throw an exception
(2) I suspect no-one has ever used this, because it's not really that useful since it doesn't refer to x/y in the viewport (unless the mouse click event can refer to the position in the underlying div, which I suppose is possible, but I don't think it does). It would be more useful if the offset of the left hand edge of the viewport could be factored in. I'm still using the pre-frozen row version, so it's easy for me, but I'm not sure how to get that offset in this version.

I used example-simple for the browser, made the ``` w <= x``` correction, changed the width to 300px and the height to 200px, and here's what I get:

![SlickGrid2343](https://github.com/6pac/SlickGrid/assets/143957/a7be72b5-5748-4c94-a9fd-f46f74ed3361)

**Comment by ghiscoding** [comment]
> (1) I think negative inputs should throw an exception, and that it should never return negative indices in the hash.

I don't think throwing is a good idea, that mean user would have to add a try/catch, I would rather have a negative value to compare against `>= 0` to know the coordinate is inside the grid or not

Yes it's the grid viewport canvas not the actual full window viewport. 

> I used example-simple for the browser, made the ` w <= x` correction, changed the width to 300px and the height to 200px, and here's what I get:

that seems to be fixing it, previously the code `if (cell < 0)` was impossible to reach (probably still is unreachable) and I'm not sure did we still need that too or just the `<=`? Also like I said above, I would rather not throw for coordinates outside the canvas

**Comment by 6pac** [comment]
Yep I think we can lose ```if (cell < 0)```.  

I'll leave the decision about negative inputs to you, but if we're talking about a point on the virtual grid, a negative value simply makes no sense, which I think should throw, or as alternative return a placeholder value (```null``` or ```(-1,-1)``` - I think ```null ``` is a better choice, but I also note that it's quite likely to lead to a harder-to-diagnose exception being thrown!).

**Comment by ghiscoding** [comment]
@6pac I was thinking returning `null` is better than throwing but it is actually easier to implement since returning `null` would require revisiting all plugins expecting a row/cell but throwing will still return same output type... so let's go with the throw. I've opened #968 could you please take a look.

**Comment by ghiscoding** [comment]
actually after testing the throw error approach with auto-scrolling, it throws a bunch of errors when we move our mouse outside of the canvas (which is necessary for the auto-scroll to work). So I don't think the throw is the best approach anymore.

**Comment by 6pac** [comment]
sure. I'd argue that since the calling code must do a calculation of the offset on the virtual canvas, it should be checking for negatives too. However it's not worth a breaking change. Support your choice.

**Comment by ghiscoding** [comment]
just in case you didn't look at the PR, I do check for negative values, I added condition so that it never returns a number more than `-1` (prior to the PR, we could have had `{ row: -90, cell: -30 }` but that won't happen anymore, the max you'll get is `{ row: -1, cell: -1 }`)

https://github.com/6pac/SlickGrid/blob/1f3f84a25c7d520bf6ec07bf5361e866b3e8ca97/src/slick.grid.ts#L5562-L5568

**Comment by ghiscoding** [comment]
@pbower the fix for `getCellFromPoint()` is now available in all SlickGrid repos, not just in here but also in all the other repos that I maintain. Cheers

**Comment by pbower** [comment]
That's awesome, great! Thanks for letting me know.
