### ISSUE TITLE
Nested Column Header / Column Header Groups

### ISSUE THREAD

**Issue by SuberFu** [6pac/SlickGrid#99]
How viable is it to merge something like this in?
https://hariharanpalani.github.io/SlickGrid/examples/example-HeaderGrouping.html
In short, allow column header groups.

**Comment by 6pac** [comment]
Good job with the example. 

I'm a bit worried about changing the column array to a tree, though. A lot of the code depends on the columns being an array.

I think you would be much better off designing it as an unrelated 'title bar' with areas matched to the column spans.
I'll check, I've been in the process of adding something related to this for a while.

**Comment by 6pac** [comment]
just added ```example-column-group``` to the repo. This is what you have done, but in a simpler way. There are various possibilities for what happens when row are re-ordered, for example row groups move together, or they repeat in different places (will the wording fit?). I have chosen not to support row reorder or resizing.

You may want to check out ```example-draggable-grouping.html``` for a sample of something that heavily modifies the header dragging behaviour.
