### ISSUE TITLE
The GridMenu is stay on the same place if the block table moved

### ISSUE THREAD

**Issue by Berdmanfolk** [6pac/SlickGrid#997]
### Describe the bug

Hello!
The GridMenu is stay on the same place if the block table moved.
The gridMenu have to move also with table block or to auto close, when then the block table moved. 

### Reproduction

I have use slickgrid in widget like on the main screen https://golden-layout.com/

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | 5.8.1|
| SlickGrid | VERSION |
| TypeScript          | 5.8.1|
| Browser(s)          | 5.8.1 |
| System OS           | windows 10|
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
- [X] Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
that is expected since the Grid Menu is appended to the `body` with an absolute position. I never have this problem since most of my grids take the entire available space and I never scroll the body itself. Also note that there are a few other plugins that also append to the body, like ColumnPicker, HeaderMenu, CellMenu, ContextMenu, ...

**Comment by ghiscoding** [comment]
I think you should handle that yourself

```js
document.body.addEventListener('scroll', () => {
  gridMenu.hideMenu();
});
```

**Comment by ghiscoding** [comment]
closing since it works as expected, as I mentioned the Grid Menu and other plugins are appended to the `body` and if something changes in your page then you should handle closing the Grid Menu (or other plugins) yourself per the suggestion provided above. Doing a quick test with scrolling the browser does work as expected, so I don't think that we can do anything on our side, it's your code and it's for you to fix it

![msedge_YFgI4C4wju](https://github.com/6pac/SlickGrid/assets/643976/724c3cbc-9116-409c-a060-5f3abc420ae2)
